/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.knowledge.jsonc --include-runtime=false worker-knowledge-configuration.d.ts` (hash: 315b95cde4421934822e83387ed56160)
interface __BaseEnv_Env {
	RESEARCH_ORIGINALS: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	ARTICLE_QUEUE: Queue;
	INTERNAL_SERVICE_TOKEN_SECRET: SecretsStoreSecret;
	THESISFORGE_PUBLICATION_TOKEN_SECRET: SecretsStoreSecret;
	FINANCIAL_DATASETS_API_KEY_SECRET: SecretsStoreSecret;
	AI: Ai;
	AI_GATEWAY_ID: "default";
	X_REDIRECT_URI: "https://thesisforge-dashboard.davidwallach2.workers.dev/api/x/callback";
	SUPABASE_URL: string;
	X_CLIENT_ID: string;
	X_ACCESS_TOKEN: string;
	X_REFRESH_TOKEN: string;
	X_CREDENTIAL_VAULT: DurableObjectNamespace<import("./src/knowledge-pipeline").XCredentialVault>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/knowledge-pipeline");
		durableNamespaces: "XCredentialVault";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_GATEWAY_ID" | "X_REDIRECT_URI" | "SUPABASE_URL" | "X_CLIENT_ID" | "X_ACCESS_TOKEN" | "X_REFRESH_TOKEN">> {}
}
