"""Single source for the desk rulebook: docs/rules/<id>.md and the public.desk_rules seed.
Numbers come from tools/court (sim.py, grid*.py, replay.py) on the 2026-09-26 ledger.
MC = Monte Carlo, one year at ledger pace (QUANTANAMO 100, ODDSBORNE 150, BANDIT 400 trades),
returns bootstrapped from each steward's real trade_outcomes, re-centred to a true Sharpe/trade.
P(DD50) = chance of a >= 50% peak-to-trough drawdown within the year; ruin = book < 20% of start."""

RULING_DATE = "2026-09-26"

RULES = [
dict(
  id="edge-max-stake", title="Edge-scaled max stake (proven-edge growth)",
  status="in_force", status_after="in_force", verdict="amend", needs_david=False,
  purpose="Stops an unbounded requested size (the $200 Miami bet on a $490 book) while letting a proven edge compound.",
  mechanism="`private.edge_max_stake`: unproven (n < 10 or LCB <= 0) gets the starter; proven gets max(starter, min(book x 0.5 x LCB / sd^2, starter x 2^(1 + (n - 10) / 5))). LCB = mean - sd/sqrt(n) of return on stake. `sized_notional = min(requested, max_stake, cash)`.",
  paths=["supabase/schemas/22_edge_scaled_stake.sql", "supabase/schemas/23_edge_stake_reason.sql", "supabase/schemas/37_court_rulings.sql", "supabase/schemas/38_edge_max_stake_null_thesis.sql", "supabase/schemas/47_backtest_credit_live_gated.sql"],
  growth="Once proven, the cap is half-Kelly on the lower bound, which is the growth-optimal size under parameter uncertainty (full Kelly on a noisy mean overbets). The doubling-per-5-trades brake lets a real edge reach ~40% of book by n = 20. At Sharpe 0.2/trade the proposed rules reach a median 28x (BANDIT) and 8x (ODDSBORNE) in a year.",
  ruin="Without it, size is whatever the steward requests. ODDSBORNE's 40%-of-book loss on 2026-09-20 is the case it prevents. Half-Kelly on LCB never bets more than half the edge-optimal fraction.",
  statistics="The 1-sigma LCB with continuous monitoring falsely marks a zero-edge thesis proven in 47-69% of MC paths within a year. A 2-sigma bound cuts that to 9-23%, but it delays real proof (QUANTANAMO at Sharpe 0.2: 14 -> 38 trades) and cuts BANDIT's median growth at Sharpe 0.2 from 28.4x to 9.8x. With drawdown scaling as the backstop, false proofs cost little: P(DD50) at zero edge is 9.3% at 1 sigma vs 4.7% at 2 sigma.",
  incentives="A steward could inflate `requested` to get more size. That no longer helps: the cap binds, and the multiplier that rewarded inflation is struck (see confidence-multiplier). Only closed, priced, non-paper trades count, so the n gate can't be padded with paper trades.",
  evidence="MC grid (tools/court/grid.json, grid2.json). Live: every thesis is unproven today (max n = 6 per thesis; BANDIT has 35 at steward level with LCB -7.4%).",
  ruling="Uphold the proven-edge formula at 1 sigma. Amend so n and the moments include discounted backtest evidence (backtest-evidence-credit) and so the cap is multiplied by the steward drawdown scale instead of per-thesis loss halving.",
  amendment="n_eff = n_live + backtest weight (backtest-evidence-credit: none below 3 live trades, then min(sum 0.5 x n_backtest, 5, n_live / 2) x survivor factor), with the backtest mean = deflated Sharpe x spread; the spread is the live spread (migration 47). The cap is multiplied by the scale from `private.steward_drawdown`. The starter is a share of current book.",
  growth_cost="None vs current; raises growth (loss halving removed).", ruin_reduction="Bounds every entry; half-Kelly on LCB.",
  interactions="starter-stake, drawdown-scaling, backtest-evidence-credit, confidence-multiplier, entry-cap-snapshot.",
  next_review="2026-10-26"),
dict(
  id="starter-stake", title="Starter stake for unproven theses (equal 3% book risk per bet)",
  status="in_force", status_after="in_force", verdict="amend", needs_david=False,
  purpose="Lets an unproven thesis trade (learning comes from trade count, not size) without a big loss before there is evidence.",
  mechanism="starter = 0.03 x current book / steward bet volatility (`private.steward_bet_vol`: sd of return on stake over the steward's closed priced non-paper trades, floored at 0.25; 1.0 while n < 5), x the steward drawdown scale. On 2026-09-26: QUANTANAMO sd 0.222 -> floor 0.25 -> 12% of book = $660; BANDIT sd 0.449 -> 6.68% = 0.1205 SOL (x0.987 = 0.119); ODDSBORNE sd 1.957 -> 1.53% = $4.24 (x0.5 = $2.12). History: fixed dollars ($250 / $15 / 0.10 SOL) until migration 37, then the same as a book share until migration 41.",
  paths=["supabase/schemas/22_edge_scaled_stake.sql", "supabase/schemas/37_court_rulings.sql", "supabase/schemas/41_court_decisions.sql"],
  growth="A fixed-dollar starter never compounds: after a 2x the starter is 2.5% of book, not 5%. A book-share starter keeps pace with the book. The starter LEVEL is the bigger growth question. A flat ~5% of book is a very different risk per steward: book volatility per unproven trade is ~1.25% for QUANTANAMO (stocks with stops, sd of return on stake 0.22-0.25), 2.5% for BANDIT (sd 0.45) and 10.6% for ODDSBORNE (binary, sd 1.96).",
  ruin="Fixed dollars get riskier as the book shrinks. MC at zero edge: ODDSBORNE ruin 10.1% with the fixed $15, 0.1% with a book share.",
  statistics="The starter should be calibrated to stake volatility, not a flat %. A vol-normalized starter, stake = v x book / sd(return on stake), gives every steward the same book risk per unproven bet.",
  incentives="With a flat %, the steward whose instruments are most volatile gets the most book risk per bet (ODDSBORNE). Vol-normalizing removes that tilt.",
  evidence="MC (grid2.json): QUANTANAMO at Sharpe 0.1/0.2, P(2x in a year) is 10.7%/44.7% at today's starter vs 18.5%/55.6% at v = 4% (16% of book), with P(DD50) <= 0.3% either way (<= 1.5% with a 5% chance of a -40% gap per trade). ODDSBORNE at zero edge: P(DD50) 50.8% at today's 5.4% vs 1.1% at v = 4% (2.0% of book).",
  ruling="Amend (shipped in two steps): book share, not fixed dollars (37); level set to equal risk per bet at v = 3% (41, decided 2026-09-26 by the parent agent under David's delegation). The 0.25 sd floor stops a lucky low-variance sample from inflating the starter (max starter 12% of book).",
  amendment="starter = 0.03 x book / max(steward sd of return on stake, 0.25) (1.0 while the steward has < 5 trades), x drawdown scale. Proven theses keep half-Kelly on the LCB, never below the starter.",
  growth_cost="Negative for QUANTANAMO ($250 -> $660: MC P(2x) at Sharpe 0.2 rises from 44.7% toward the v = 3-4% range); ODDSBORNE smaller ($15 -> $4.24 before scale).", ruin_reduction="ODDSBORNE zero-edge P(DD50) 50.8% at 5.4% of book vs ~1-2% at v = 3-4%; QUANTANAMO P(DD50) stays <= 1.5% with gap stress.",
  interactions="edge-max-stake, drawdown-scaling.",
  next_review="2026-10-10"),
dict(
  id="loss-streak-halving", title="Per-thesis consecutive-loss halving (x0.5 per loss, floor x0.25)",
  status="in_force", status_after="repealed", verdict="strike", needs_david=False,
  purpose="Meant to cut size when a thesis is failing.",
  mechanism="`private.edge_max_stake` multiplied the cap by 0.5^min(loss_streak, 2).",
  paths=["supabase/schemas/23_edge_stake_reason.sql", "supabase/schemas/37_court_rulings.sql"],
  growth="It cuts size right after losses, regardless of edge. Under the same starter, MC growth with halving vs drawdown scaling: BANDIT at Sharpe 0.1 median 1.74x vs 1.98x, P(2x) 52.5% vs 62.9%; at Sharpe 0.2 17.8x vs 28.4x. QUANTANAMO at Sharpe 0.2: P(2x) 33% vs 44.7%.",
  ruin="Drawdown scaling gives the same or better ruin protection: BANDIT P(DD50) 12.5% (halving) vs 9.9% (drawdown) at Sharpe 0.1, and 11.3% vs 9.3% at zero edge. For ODDSBORNE at a 5.4% starter, halving has the lower P(DD50) (42% vs 51% at zero edge), but only because it shrinks an oversized starter. A correctly sized ODDSBORNE starter makes both ~0%.",
  statistics="Loss streaks carry no information: BANDIT P(loss | previous loss) 0.53 vs P(loss) 0.51, lag-1 autocorrelation 0.004 over 35 trades. The edge estimate (LCB) already absorbs the losses. Halving punishes the same evidence twice.",
  incentives="It's per thesis, so a steward escapes it by registering a new thesis (the new-thesis escape). It also rewards cutting a loser early to reset the streak, whatever the thesis's real invalidation says.",
  evidence="Ledger autocorrelation (tools/court). MC grid2 book5_halving vs book5_ddscale. Replay of real sequences (replay.json): BANDIT +2.6% with halving vs -0.7% with the proposed rules, on one 35-trade path. That's inside noise; the MC is the evidence.",
  ruling="Strike. Replace with steward-level drawdown scaling (drawdown-scaling).",
  amendment="Removed from `private.edge_max_stake`. `loss_streak` stays in the stats for information.",
  growth_cost="Removing it raises growth (BANDIT median +14% at Sharpe 0.1).", ruin_reduction="Replaced by drawdown scaling, which has equal or lower P(DD50) at the same starter.",
  interactions="drawdown-scaling, new-thesis-escape.",
  next_review="2026-12-26"),
dict(
  id="drawdown-scaling", title="Steward-level drawdown scaling",
  status="proposed", status_after="in_force", verdict="amend", needs_david=False,
  purpose="Cuts risk when the BOOK is in trouble (the thing that can actually be ruined), not when one thesis label had a streak.",
  mechanism="scale = 1.0 at <= 10% below the steward's closing high-water mark, falling linearly to 0.5 at >= 40%. The HWM is the max of each UTC day's last book observation, used because intraday entry-time snapshots include double-count artifacts. It multiplies every thesis's cap, proven or not. `private.steward_drawdown`.",
  paths=["supabase/schemas/37_court_rulings.sql"],
  growth="No cost in normal noise (<= 10%). The floor of 0.5 keeps a recovering book trading at half size, so recovery isn't choked. MC growth equals or beats halving everywhere at the same starter.",
  ruin="Anti-martingale at the book level: sizes shrink as the book approaches ruin. BANDIT MC at zero edge: P(DD50) 35.9% with no control vs 9.3% with drawdown scaling; ODDSBORNE ruin 7.4% vs 0.1%.",
  statistics="Uses the book path, which is the actual ruin variable. No thesis-level noise. The 10% dead band sits above normal noise (QUANTANAMO's worst close-to-close drawdown is 16%; BANDIT's intraday swings reach 30%).",
  incentives="Steward-wide, so it can't be escaped with a new thesis. Deposits would reset the HWM mechanics; none have happened. A deposit should be recorded as a flow before this rule reads it.",
  evidence="Live on 2026-09-26: QUANTANAMO HWM $6,098.56 -> 9.8% below -> x1.00; ODDSBORNE HWM $524.76 -> 47.2% below -> x0.50; BANDIT HWM 2.0207 SOL -> 10.8% below -> x0.987.",
  ruling="Enact.", amendment="New rule (migration 37).",
  growth_cost="0 inside a 10% drawdown; x0.5 at worst.", ruin_reduction="BANDIT P(DD50) 35.9% -> 9.3%; ODDSBORNE ruin 7.4% -> 0.1% (zero edge).",
  interactions="Replaces loss-streak-halving; closes new-thesis-escape; multiplies edge-max-stake.",
  next_review="2026-10-26"),
dict(
  id="new-thesis-escape", title="New-thesis escape from a loss-reduced cap",
  status="in_force", status_after="repealed", verdict="strike", needs_david=False,
  purpose="The problem: per-thesis halving could be escaped by registering a new thesis. The first fix (steward-wide cap on every unproven thesis, #97) pinned QUANTANAMO themes at $62.50 and was reverted (#98).",
  mechanism="Resolved structurally. Loss halving is struck, and the only loss response is steward-wide drawdown scaling, which applies to every thesis, new or old. A new thesis gets the starter x the steward's drawdown scale, the same as any unproven thesis.",
  paths=["supabase/schemas/34_revert_steward_wide_starter.sql", "supabase/schemas/37_court_rulings.sql", "supabase/schemas/41_court_decisions.sql"],
  growth="#97's rule cut QUANTANAMO's unproven themes 75% ($250 -> $62.50) because of 3 losses on another thesis. That's a large growth cost with no ruin case: loss streaks don't predict (see loss-streak-halving). The structural fix costs nothing.",
  ruin="Covered by drawdown scaling at the book level.",
  statistics="Punishing unrelated theses for one thesis's streak treats noise as signal.",
  incentives="The remaining gap (a new QUANTANAMO thesis stated at >= 80 passed the gate with zero evidence) is closed by migration 41: the gate reads only the results score, and a thesis with < 3 effective trades is unscored and needs David. See quantanamo-80-gate.",
  evidence="#97 live numbers: every unproven QUANTANAMO theme at $62.50; reverted by #98 (migration 34).",
  ruling="Strike the problem at its root (no per-thesis punishment exists to escape). No separate rule needed.",
  amendment="None beyond loss-streak-halving and drawdown-scaling.",
  growth_cost="None.", ruin_reduction="Via drawdown-scaling.",
  interactions="loss-streak-halving, drawdown-scaling, quantanamo-80-gate.",
  next_review="2026-10-26"),
dict(
  id="confidence-multiplier", title="Half-Kelly outcome multiplier on the requested size",
  status="in_force", status_after="repealed", verdict="strike", needs_david=False,
  purpose="Scaled requested size by a half-Kelly estimate from hit rate and avg win/loss (0.5 when n < 5, 0.25 with no edge).",
  mechanism="`sized_notional = min(requested x multiplier, max_stake, cash)`. Now `min(requested, max_stake, cash)`. The multiplier is still returned for information.",
  paths=["supabase/schemas/11_outcome_rescore_sizing.sql", "supabase/schemas/22_edge_scaled_stake.sql", "supabase/schemas/37_court_rulings.sql"],
  growth="It halves an honest steward's size on every unproven thesis (n < 5 -> 0.5), on top of the starter that already exists for that.",
  ruin="Adds nothing: max_stake already bounds every entry, with a proper lower-bound edge estimate.",
  statistics="It uses raw hit rate and payoff with no shrinkage. At n = 5 a hit-rate estimate is +/- 22 points (1 sigma), so the multiplier is noise until n ~ 30, and the edge-scaled cap already handles small samples properly.",
  incentives="Directly gameable: request 2x to get 1x. An honest steward is penalized, and a gaming one isn't.",
  evidence="Structural. BANDIT's 0.45 SOL clip x 0.5 = 0.225 was already capped by max_stake. The multiplier changed nothing for a steward requesting above the cap.",
  ruling="Strike from sizing. Keep reporting it.",
  amendment="guidance: sized_notional = min(requested, max_stake, spendable cash). QUANTANAMO requested % is no longer multiplied (scheduled-run prompt). The retired workers/research mirror is left alone.",
  growth_cost="Raises honest sizes up to 2x (never above max_stake).", ruin_reduction="None lost (max_stake binds).",
  interactions="edge-max-stake.",
  next_review="2026-12-26"),
dict(
  id="outcome-rescore-confidence", title="Results re-score of thesis confidence (expected return per trade)",
  status="in_force", status_after="in_force", verdict="amend", needs_david=False,
  purpose="Tempers a steward's stated confidence with realized outcomes. Feeds the QUANTANAMO >= 80 gate and hardening/forming status.",
  mechanism="`private.thesis_results_score`: scored only with >= 3 live trades (else null, unscored). n_eff = live trades + the backtest weight (backtest-evidence-credit: verified tests, pass or fail, none below 3 live trades, then min(sum 0.5 x n, 5, live / 2) x survivor factor); mean_eff pools the live mean return on stake with the backtest deflated Sharpe x spread; sd_eff = max(live sd, 0.25); results_confidence = round(100 x Phi(mean_eff / (sd_eff / sqrt(n_eff)))). Demote hardening -> forming only when the live upper bound mean + max(sd, 0.25)/sqrt(n) < 0, or n >= 10 with mean < 0; kill only when n >= 10 and the upper bound < 0 (live only). theses.confidence (display) = results_confidence when scored, else the stated number. Only the re-score writes the results columns (guard trigger). The QUANTANAMO 80 gate does not read this score directly: it reads gate_score, the same z shrunk by sqrt(n_live / (n_live + 16)) (quantanamo-80-gate, migration 48). Was: Beta on hit rate, cap 60 and demote at n >= 5 with negative P/L.",
  paths=["supabase/schemas/11_outcome_rescore_sizing.sql", "supabase/schemas/41_court_decisions.sql", "supabase/schemas/47_backtest_credit_live_gated.sql", "supabase/schemas/48_quantanamo_gate_small_sample.sql"],
  growth="Hit rate isn't edge. QUANTANAMO's style wins big and loses small (winners avg +30% of stake, losers -11%; breakeven hit rate 27%). A thesis hitting 35% at that payoff earns ~+3.2% per trade, but its confidence converges to 35 and it can never pass the 80 gate. The 5-trade demotion blocks 41% of genuinely good theses (true Sharpe 0.1/trade) and 33% at Sharpe 0.2.",
  ruin="Small: bad theses are already small via max_stake, and demotion only affects QUANTANAMO autonomy.",
  statistics="Five trades can't tell a Sharpe-0.1 thesis from zero: P(sum < 0) = Phi(-0.1 sqrt 5) = 41%. A hit-rate Beta prior ignores payoff asymmetry.",
  incentives="Pushes a steward toward high-hit-rate, low-payoff trades (take profits early, let losers run) just to keep confidence high: the opposite of what compounds.",
  evidence="Closed-form above; ledger payoff stats (QUANTANAMO 7 trades: hit 29%, payoff ratio 2.7).",
  ruling="Amend (shipped in migration 41; decided 2026-09-26 by the parent agent under David's delegation). Status changes on the 2026-09-26 re-run: none (no thesis has a negative upper bound or n >= 10).",
  amendment="Score on expected return per trade (above). Stated confidence is display only.",
  growth_cost="Removes the permanent block on asymmetric theses.", ruin_reduction="Demotion/kill now needs real evidence of negative edge.",
  interactions="quantanamo-80-gate, edge-max-stake, backtest-evidence-credit.",
  next_review="2026-10-26"),
dict(
  id="quantanamo-80-gate", title="QUANTANAMO autonomous-entry gate: hardening thesis with results score >= 80",
  status="in_force", status_after="in_force", verdict="amend", needs_david=False,
  purpose="David approves anything below 80; autonomy only for strong theses.",
  mechanism="`steward_sizing_guidance`: QUANTANAMO entry_allowed needs status = hardening and `results_basis.gate_score` >= 80 (reason `quantanamo_unscored` when unscored, else `quantanamo_confidence_gate`). gate_score = round(100 x Phi(z x sqrt(n_live / (n_live + 16)))), where z is the results-score z (outcome-rescore-confidence). A neutral prior of 16 zero-mean trades: at 3 live trades the gate needs a raw score near 98, at 40 trades near 84, and it fades toward the raw 80. The shown results_confidence is unchanged, and only the re-score writes either number. Backtests count in z but not in the prior, and still can't open the gate alone: no score below 3 live trades (migration 47).",
  paths=["supabase/schemas/22_edge_scaled_stake.sql", "supabase/schemas/41_court_decisions.sql", "supabase/schemas/48_quantanamo_gate_small_sample.sql", "docs/scheduled-run-prompt.md"],
  growth="The gate does not size the bet, so doubling odds do not move. One year, 1,500 paths, current stake rule, no backtests: Sharpe 0 median 0.952x and P(2x) 3.3%; Sharpe 0.2 median 1.87x and P(2x) 54.1%; Sharpe 0.4 median 53.94x and P(2x) 99.5%. The cost is time to autonomy, not size: median live trades until the gate opens goes from 9 to 21 at Sharpe 0.2 (still open by trade 80 on 89.4% of paths) and from 6 to 12 at Sharpe 0.4 (99.8% open by 80). A lower-bound gate (z - 0.84) would have left a Sharpe-0.2 thesis unautonomous past 80 trades 36% of the time (censored median 53). This prior does not.",
  ruin="False opens before 10 live trades fall from 31.0% to 8.5% at zero edge. Book ruin stays 0. P(drawdown >= 50%) stays 0.3% at Sharpe 0, 0.4% at Sharpe 0.2, and 0.1% at Sharpe 0.4, because size is unchanged. The size risk was already bounded by max_stake.",
  statistics="The shown score stays P(expected return per trade > 0) >= 0.8 (z >= 0.84). Reading it straight made a small sample look sure: with the spread floored at 0.25, three lucky trades clear z = 0.84 far too often, and the gate is re-checked after every trade, so the chance it has opened at some point before 10 live trades is 31% at zero edge (4,000 paths; earnings_gap_structure itself scored 92 after 3 trades with no backtest). The gate now uses z x sqrt(n_live / (n_live + 16)), the posterior z under a normal prior of 16 zero-mean trades with the same spread. That is not a fixed rail: the bar falls toward 80 as live trades accumulate (about 98 at n = 3, 84 at n = 40, 82 at n = 100). A fixed lower bound (z - 0.84, gate only) also got under 10% false opens but left a Sharpe-0.2 thesis unautonomous past 80 trades 36% of the time. Requiring the raw score to hold for 4 re-scores in a row landed at 10.7%.",
  incentives="Stated confidence still can't open the gate, and neither can the shown score on its own. gate_score is written only by the re-score, into results_basis, which the results guard already protects. Logging backtests can't spend the prior down: the fade uses n_live, while backtest weight only enters z, and a fake +0.2 Sharpe backtest cuts false opens further (26.9% -> 5.8%) rather than reopening the hole. There is no minimum trade count to wait out and no cap to route around.",
  evidence="tools/court/gate80.py (gate80.json; SIMULATION.md, section Small-sample 80 gate). 4,000 paths on the centered QUANTANAMO ledger returns. False opens before 10 live trades: 31.0% raw, 8.5% with prior 16. Median trades until the gate opens, Sharpe 0.2: 9 -> 21 (89% still open within 80 trades); Sharpe 0.4: 6 -> 12 (99.8% within 80). Sizing is untouched, so doubling odds don't move (1,500 paths, one year): Sharpe 0.2 median 1.87x, P(2x) 54.1%; Sharpe 0.4 median 53.9x, P(2x) 99.5%; ruin 0. Ledger replay in the ruling file.",
  ruling="Amend (2026-09-30, migration 48): the 80 threshold stays, but the gate reads a small-sample-shrunk score, not the shown results score. False opens before 10 live trades 31% -> 8.5%, and a real edge still reaches autonomy near when its expected evidence would have cleared 80 (Sharpe 0.2 median 21 live trades, Sharpe 0.4 median 12). No live score moves and no thesis opens the gate. Was (migration 41): gate on the raw results score, which a zero-edge thesis cleared on luck with 3-9 trades.",
  amendment="private.thesis_results_score gains gate_score = round(100 x Phi(z x sqrt(n_live / (n_live + 16)))). The re-score stores it on results_basis (gate_score, gate_prior 16) and still writes results_confidence as the unshrunk score. steward_sizing_guidance opens the QUANTANAMO gate on status = hardening and gate_score >= 80. Shown scores are not rewritten except to add the new basis keys.",
  growth_cost="None on the book: the gate does not size the bet, so P(2x) is unchanged (Sharpe 0.2: 54.1%, median 1.87x; Sharpe 0.4: 99.5%, median 53.9x). Autonomy is later, not smaller: median trades to open 9 -> 21 at Sharpe 0.2 and 6 -> 12 at Sharpe 0.4.", ruin_reduction="False opens before 10 live trades 31.0% -> 8.5% (inside the 10% target). Book ruin stays 0, since size is unchanged.",
  interactions="outcome-rescore-confidence, new-thesis-escape, backtest-evidence-credit.",
  next_review="2026-11-30"),
dict(
  id="required-invalidation", title="Required invalidation on entry (guidance + table trigger)",
  status="in_force", status_after="in_force", verdict="uphold", needs_david=False,
  purpose="Every lot has a written, priced falsifier before money goes in, so exits aren't improvised.",
  mechanism="Guidance returns missing_invalidation without p_invalidation_price > 0. `private.require_lot_invalidation` rejects a new or re-opened open lot without one.",
  paths=["supabase/schemas/22_edge_scaled_stake.sql"],
  growth="No cost: any trade can state an invalidation. It's also the input a risk-based starter would need.",
  ruin="Prevents open-ended holds of broken trades. BANDIT's -100% rugs (GTA6, ACAT) show a stop doesn't cap loss in illiquid coins. That's handled by stake size, not by this rule.",
  statistics="n/a (process rule).",
  incentives="A steward could set an absurdly far invalidation. Guidance only checks > 0, and the ODDSBORNE script checks 0 < inval < price. Follow-up: pass the entry price to guidance so it can reject inval >= entry for longs.",
  evidence="All open lots carry one (watchdog v_open_lots_missing_invalidation = 0).",
  ruling="Uphold.", amendment="Follow-up (not shipped): entry-price sanity check.",
  growth_cost="None.", ruin_reduction="Moderate (process).",
  interactions="regular-session-invalidation, starter-stake.", next_review="2027-03-26"),
dict(
  id="regular-session-invalidation", title="Equity invalidation exits fire only on regular-session prints",
  status="in_force", status_after="in_force", verdict="uphold", needs_david=False,
  purpose="Avoid full-lot exits on thin pre/after-hours prints; those set review_at_open instead.",
  mechanism="Monitor policy autonomous-position-v5, `private.is_us_regular_session` with the NYSE holiday/early-close calendar. Coins and PM are 24/7, with no session filter.",
  paths=["workers/research/src/position-decision.ts", "supabase/schemas/29_us_market_calendar.sql", "packages/contracts/src/market-calendar.ts"],
  growth="Avoids selling a good lot on a spurious extended-hours print (CODA trades thin).",
  ruin="Small cost: a real overnight break is acted on at the open, and the review flag makes sure it is. Market orders can't fill after hours anyway (broker is RTH-only).",
  statistics="Extended-hours prints are few, wide-spread trades; a single print isn't a price.",
  incentives="None.", evidence="Structural.", ruling="Uphold.", amendment="None.",
  growth_cost="None.", ruin_reduction="Neutral.", interactions="required-invalidation.", next_review="2027-03-26"),
dict(
  id="stale-book-6h", title="Entries need a book observation <= 6 hours old",
  status="in_force", status_after="in_force", verdict="uphold", needs_david=False,
  purpose="Sizing uses the real book and cash, not a stale snapshot (a stale high book would oversize).",
  mechanism="Guidance returns stale_book when the older of the equity and cash observations is > 360 minutes old.",
  paths=["supabase/schemas/22_edge_scaled_stake.sql"],
  growth="Near zero: the steward records a fresh snapshot before trading (one call).",
  ruin="Prevents sizing off a book that already fell.", statistics="n/a.",
  incentives="None; the fix is one snapshot write.", evidence="Structural.", ruling="Uphold.", amendment="None.",
  growth_cost="~0.", ruin_reduction="Small-moderate.", interactions="starter-stake, drawdown-scaling (both read the book).", next_review="2027-03-26"),
dict(
  id="thesis-status-blocks", title="Killed, rejected or unknown thesis blocks new entries",
  status="in_force", status_after="in_force", verdict="uphold", needs_david=False,
  purpose="A falsified or rejected idea (or a typo'd id) can't size an entry.",
  mechanism="Guidance: unknown_thesis, thesis_rejected, thesis_killed; sized_notional = 0.",
  paths=["supabase/schemas/21_unknown_thesis_gate.sql", "supabase/schemas/22_edge_scaled_stake.sql"],
  growth="None: a killed thesis has no edge by definition.", ruin="Stops trading a falsified idea.",
  statistics="n/a.", incentives="Can't be escaped by tagging with a non-existent id.",
  evidence="Structural.", ruling="Uphold.", amendment="None.",
  growth_cost="None.", ruin_reduction="Moderate.", interactions="new-thesis-escape.", next_review="2027-03-26"),
dict(
  id="cash-only-no-margin", title="Cash only: no margin, no leverage",
  status="in_force", status_after="in_force", verdict="uphold", needs_david=False,
  purpose="Worst case is losing the stakes. The book can't go negative or be force-liquidated.",
  mechanism="sized_notional <= spendable cash (min(cash, buying power)); the broker rejects buys needing margin.",
  paths=["supabase/schemas/14_no_position_cap.sql", "workers/broker/src/robinhood-broker-agent.ts"],
  growth="Caps total exposure at 1x book. For a proven edge, half-Kelly on LCB rarely asks for more than 1x in these books.",
  ruin="Removes the one path to losing more than the book.", statistics="n/a.",
  incentives="None.", evidence="Standing preference (David).", ruling="Uphold.", amendment="None.",
  growth_cost="Small.", ruin_reduction="Large (eliminates negative-equity paths).", interactions="portfolio-exposure.", next_review="2027-03-26"),
dict(
  id="listed-equity-registry", title="Listed-equity registry exempts real tickers from the ontology junk filter",
  status="in_force", status_after="in_force", verdict="uphold", needs_david=False,
  purpose="Real tickers (TXN, GFS, MP) aren't discarded as junk words.",
  mechanism="`public.listed_equities`, checked by `private.ontology_label_is_junk` / `isJunkOntologyLabel`.",
  paths=["supabase/schemas/26_listed_equities.sql"],
  growth="Unblocked 35 tickers and 58 candidates.", ruin="None.", statistics="n/a.",
  incentives="Only verified listings are added.", evidence="2026-09-26 sweep: 35 tickers, 58 candidates restored.", ruling="Uphold.", amendment="None.",
  growth_cost="Negative (helps).", ruin_reduction="None.", interactions="None.", next_review="2027-03-26"),
dict(
  id="entry-cap-snapshot", title="Cap-at-entry snapshot and ledger watchdog",
  status="in_force", status_after="in_force", verdict="uphold", needs_david=False,
  purpose="Every entry is audited against the cap in force when it was made. Breaches and missing invalidations surface twice a day.",
  mechanism="`max_stake_at_entry` trigger; `v_ledger_integrity` (entry_over_max_stake at > 1.10x); `v_invalidation_breaches`; `v_open_lots_missing_invalidation`; `v_ledger_watchdog`.",
  paths=["supabase/schemas/24_ledger_watchdog.sql", "supabase/schemas/30_max_stake_at_entry.sql"],
  growth="None (measurement).", ruin="Catches rule bypasses.", statistics="n/a.",
  incentives="Makes bypass visible.", evidence="Live counts in the health routine.", ruling="Uphold.", amendment="None.",
  growth_cost="None.", ruin_reduction="Detective.", interactions="edge-max-stake.", next_review="2027-03-26"),
dict(
  id="backtest-evidence-credit", title="Out-of-sample backtest evidence counts both ways, as a small correction to live results",
  status="in_force", status_after="in_force", verdict="amend", needs_david=False, ruling_date="2026-09-27",
  purpose="Lets real out-of-sample evidence move a thesis's score and proof a little either way, pass or fail, without letting backtests stand in for live trades or rewarding a steward for logging only winners.",
  mechanism="`public.thesis_backtest_evidence`, append-only for stewards, one row per (thesis, test). A trigger copies from the linked `strategy_tests` row and its research cycle: rules_locked_at (preregistered_at), results_at (tested_at), deflated_sharpe, test_status, thesis_trials (non-placeholder tests the thesis had run by then), and sets verified / ineligible_reason. A row is verified when its test is survived or killed (placeholder, lookahead_invalid, queued and unverified earn nothing), has a price source and a date window, rules_locked_at < results_at, a stored deflated Sharpe, trials >= thesis_trials, out_of_sample and costs_included. A change to the test row re-derives it. A test whose params mark point-in-time data unverified (any `*point_in_time` key not 'true', e.g. test 32's estimate_point_in_time = unverified), or that is a filtered subset of another test on the same thesis (`parent_test_id`, e.g. test 32 of test 31), gets no row at all: the insert is refused. `private.thesis_edge_evidence(thesis, n_live)` gives no credit below 3 live trades; otherwise weight = min(sum 0.5 x n, 5, n_live / 2) x the pooled survivor factor (1 - missing_share for a survivors-only test, 0.5 if unknown) and credited mean = deflated Sharpe x spread, pooled by 0.5 x n x factor, pass or fail. `private.edge_max_stake` and `private.thesis_results_score` add it to the live trades with no further shrink; the spread stays the live spread. `v_thesis_backtest_evidence` lists every row (verified, why not, for/against); `v_backtest_tests_unlogged` lists completed thesis tests (thesis named in the test params) with no row, leaving out the point-in-time-unverified and subset tests; `v_thesis_scorecard` shows the weight the re-score applied.",
  paths=["supabase/schemas/37_court_rulings.sql", "supabase/schemas/46_backtest_evidence_symmetric.sql", "supabase/schemas/47_backtest_credit_live_gated.sql"],
  growth="Doesn't choke growth; it gives back most of what 46 cost. MC (tools/court/evidence_gate.py, 2 preregistered 200-trade tests per thesis at 17 trials, one survivors-only, 1,500 paths, one year): QUANTANAMO at Sharpe 0.2 P(2x) 55.0% with no backtests, 48.5% under 46, 53.7% now; median trades to proven 14 / 20 / 15. BANDIT at Sharpe 0.2 median multiple 28.6x / 25.0x / 28.2x. The case that matters for earnings_gap_structure, a real live edge whose mechanical backtest has none: QUANTANAMO P(2x) 41.5% under 46 vs 51.2% now, BANDIT 21.4x vs 26.1x. The starter is untouched, so learning pace (trade count) is the same under every rule.",
  ruin="Neutral. P(book < 20% of start) is 0 in every cell under every rule; QUANTANAMO P(DD50) <= 0.5% everywhere. Because backtests are now a small share of the evidence, some of 46's protection against false proofs goes: zero-edge theses proven within a year QUANTANAMO 47.5% (no backtests) / 29.6% (46) / 41.2% (now), BANDIT 61.3% / 44.9% / 56.0%; BANDIT P(DD50) at zero edge 28.5% / 24.5% / 26.1%. Those proofs get half-Kelly on a small LCB and the drawdown scale, which is why ruin stays at 0. Sizing today: earnings_gap_structure stays at the starter ($660.08, 12% of book) with 7.98 effective trades.",
  statistics="Every completed, preregistered test counts whichever way it came out, so logging only winners buys nothing. The credited mean is the deflated Sharpe times the spread: the mean left after subtracting what the best of the thesis's N tries would show by luck (test 31: -0.1228 x 6.20% = -0.76% per trade, vs its raw -0.35%). Deflation already corrects selection, so there's no extra 50% shrink, and it treats a pass and a fail the same way. The weight is capped because a backtest of a mechanical rule isn't the thesis as traded (test 31 skips the discretionary selection the live book does), survivors-only samples are biased, and correlated same-night events overstate n: 714 trades count as at most 5 effective trades, and never more than half the live count. The backtest spread (6.2%) never narrows the live spread (floored at 0.25). Subsets aren't new evidence: test 32 re-used test 31's 714 events filtered to 249 serial EPS beaters, so logging it would count those 249 trades twice and would let a steward pile up weight by slicing one sample. A test with a parent_test_id on the same thesis counts as a trial (it raises the thesis's trial count, which deflates later tests), never as another row. Overlap that isn't declared (a DJIA name can sit in both test 30 and test 31, under different exit rules) is bounded by the pooled cap of 5. The small-sample hole this note flagged (the raw score opens the 80 gate at some point on 31% of zero-edge paths, and earnings_gap_structure scored 92 after 3 trades with no backtest) is closed by quantanamo-80-gate, migration 48: the gate reads a score shrunk toward 50 by 16 zero-mean trades, and the shown score is unchanged. Backtest credit was the wrong tool for it.",
  incentives="Can't be gamed for more than a nudge. With a fake +0.2 Sharpe backtest on a zero-edge thesis, false proofs are 47.7% vs 47.5% with no backtest (QUANTANAMO) and 62.3% vs 61.3% (BANDIT), and the 80 gate opens less often, not more (26.6% vs 31.2%), because every test is deflated by the thesis's trial count. Backtests alone can't score a thesis or open the gate: no credit and no score below 3 live trades. Lock time, results time, deflated Sharpe, test status and the thesis's trial count come from the test record, not the steward. Under-counting trials, skipping preregistration, a missing source or window, or a voided test (lookahead_invalid, placeholder) all make a row unverified and worth zero. A disputed point-in-time input gets no row at all (test 32's EPS estimates have no as-of timestamp), and slicing one sample into filtered subsets buys nothing (a parent_test_id on the same thesis is refused). Logging many tests doesn't add up: the pooled weight is capped at 5. Rows are append-only for stewards, and `v_backtest_tests_unlogged` shows any completed thesis test that should have been logged and wasn't.",
  evidence="tools/court/evidence_gate.py (evidence_gate.json; SIMULATION.md, section Live-gated backtest credit). Ledger replay of earnings_gap_structure's six live trades (DG, SNOW, AOUT, ASAN, OCC, ZUMZ): results score after each trade with no backtest / 46 / now: unscored, unscored, 92 / 73 / 88, 81 / 66 / 77, 69 / 60 / 66, 56 / 52 / 54. Test 31 (trial 17, stored row): 714 trades, hit 49.0%, mean -0.346%, sd 6.20%, deflated Sharpe -0.1228, survivors only (34.6% of events missing), 30 bps. Test 30 (trial 16, stored row): 13 trades, hit 53.8%, mean +1.78%, sd 9.64%, deflated Sharpe -0.329, 10 bps, 38 of 336 events missing. Test 32 (trial 18: test 31's events filtered to a 3-quarter EPS beat streak, 249 trades, killed, deflated Sharpe -0.211): no row (estimates not point-in-time verified; subset of test 31). Pooled: weight 1.98 (min(363.5, 5, 3) x 0.659), deflated mean -0.82% per trade.",
  ruling="Amend (2026-09-27, migration 47, following 46): pass or fail still counts, but backtest credit is live-gated and small. No credit or score below 3 live trades; weight min(5, live / 2) x (1 - missing share) for survivors-only; credited mean = deflated Sharpe x spread; unverified tests earn nothing. 47 re-derives test 31, logs test 30, leaves test 32 out (point-in-time unverified, and a subset of test 31), and re-scores: earnings_gap_structure 52 -> 54 (56 before 46); no other score moves. Was (46): up to 20 effective trades from before the first live trade, emax-deflated mean shrunk 50%; (37): survivors only.",
  amendment="thesis_backtest_evidence gains test_status, thesis_trials, verified, ineligible_reason (trigger-derived); weight = min(0.5 x n, 5) x survivor factor; mean_ret_deflated = deflated Sharpe x sd. private.thesis_edge_evidence(text) is replaced by (text, integer) with the live gate and cap; edge_max_stake and thesis_results_score drop the 50% shrink and use the live spread; the score needs >= 3 live trades. A strategy_tests update (including params_json) re-derives its evidence. Point-in-time-unverified tests and filtered subsets of another test on the same thesis get no row (the insert is refused; v_backtest_tests_unlogged leaves them out). v_thesis_backtest_evidence stops reading strategy_tests; 46's strategy_tests read grant to oddsborne_worker / bandit_worker stays (v_backtest_tests_unlogged still reads strategy_tests as the invoker).",
  growth_cost="Close to none: QUANTANAMO Sharpe-0.2 P(2x) 53.7% vs 55.0% with no backtests (46: 48.5%); with a real live edge and a no-edge backtest, 51.2% vs 46's 41.5%.", ruin_reduction="Neutral: ruin 0 in every cell; gives back part of 46's cut in zero-edge false proofs (QUANTANAMO 29.6% -> 41.2%, no backtests 47.5%) in exchange for not letting backtests outweigh live trades.",
  interactions="edge-max-stake, outcome-rescore-confidence, quantanamo-80-gate.", next_review="2026-11-27"),
dict(
  id="portfolio-exposure", title="Portfolio exposure: open risk <= 10% of book (gap-prone lots at full notional)",
  status="proposed", status_after="in_force", verdict="amend", needs_david=False,
  purpose="Per-entry caps don't bound total or correlated exposure across open lots, and an invalidation line doesn't bound a lot that can gap straight through it.",
  mechanism="`private.open_risk_lots()` (per lot, `public.v_exposure_lots`) summed by `private.steward_open_risk` (`public.v_exposure_usage`), in the book unit, `risk_basis` per book. QUANTANAMO equities `to_invalidation`: qty x max(mark - invalidation_price, 0) (no invalidation: qty x mark; unmarked: 0, flagged). ODDSBORNE binaries and BANDIT memes `full_notional`: every open binary at price x contracts (mark, else average cost) and every meme lot at its full cost basis (qty x average cost, else qty x mark). Budget 10% of book. Guidance sizes a new entry to fit: min(requested, max_stake, cash, headroom / risk fraction), where the fraction is 1 for full_notional books and (entry - invalidation) / entry for equities (1 without p_entry_price); no headroom -> `exposure_cap`. Guidance, v_exposure_usage and the v_ledger_watchdog `exposure` summary carry `risk_basis`.",
  paths=["supabase/schemas/41_court_decisions.sql", "supabase/schemas/44_exposure_gap_full_notional.sql"],
  growth="Any cap here limits concentration into the best ideas. Full notional on the gap-prone books makes BANDIT effectively one clip at a time (budget 0.180 SOL vs a 0.119 starter: one clip leaves 0.061 SOL of headroom) and lets ODDSBORNE hold about 13 of today's $2.12 tickets ($27.69 budget).",
  ruin="Gap risk is the real tail. A Polymarket binary goes from its mark to 0 on one score, and a meme can rug in one block, so the -40% meme line and the outcome-price line on a binary bound nothing; counting them to invalidation understated BANDIT's risk per clip by 60% (0.4 x notional vs the whole notional). Equities keep to-invalidation, since a stop on a listed name usually fills near its line (gaps excepted). QUANTANAMO on 2026-09-26 (9/25 after-hours marks, lines raised at 3:08 PM PT): NBIS $80, CIFR $79, CODA $193 = $351 (6.4% of $5,501). Before the raise: NBIS $161, CIFR $186, CODA $308 = $654 (11.9%, over budget).",
  statistics="Needs a correlation estimate by theme; with n this small, use theme membership as the proxy. For binaries and memes the loss distribution is bimodal (full loss or not), so the right risk unit is the notional, not a distance to a line.",
  incentives="Without it, a steward can stack correlated starters across several theses. To-invalidation on a gap-prone lot rewards writing a tight line the venue can't honor; full notional removes that lever.",
  evidence="Open position_episodes, pm_positions and meme_positions on 2026-09-26 (v_exposure_lots); venue mechanics: a binary resolves to 0 or 1, and a meme pool can be pulled in one block.",
  ruling="Enact option (b) at R = 10% (migration 41; decided 2026-09-26 by the parent agent under David's delegation). Amended the same day (migration 44): ODDSBORNE binaries and BANDIT memes count at full notional, equities keep to-invalidation. After QUANTANAMO raised its lines it is at 6.4% (was 11.9%, blocked); ODDSBORNE and BANDIT have no open lots (0%).",
  amendment="Open risk <= 10% of book per steward, gap-prone lots (binaries, memes) at full notional and equities to invalidation; guidance sizes down or blocks and reports `risk_basis`.",
  growth_cost="Caps stacking; at a 10% invalidation distance equities still allow ~100% of book in positions. BANDIT holds about 1.5 starters at once (0.180 SOL budget), ODDSBORNE about 10% of book in open tickets.", ruin_reduction="Bounds the loss if every open lot hits its invalidation at once (equities) or goes to zero (binaries, memes) to 10% of book.",
  interactions="cash-only-no-margin, required-invalidation, edge-max-stake, starter-stake.", next_review="2026-10-26"),
dict(
  id="shadow-exits", title="Shadow (paper) exit tracking",
  status="in_force", status_after="in_force", verdict="uphold", needs_david=False,
  purpose="Test alternative exit rules without trading them. Promote a rule only once it beats real exits.",
  mechanism="`meta.paper_<rule>` on lot rows; `v_shadow_exits`, `v_shadow_exit_scorecard` (promotable at n >= 10 and LCB of paper - real > 0).",
  paths=["supabase/schemas/32_shadow_exits.sql", "supabase/schemas/33_shadow_exits_definer.sql"],
  growth="Positive: finds better exits at no cost.", ruin="None.",
  statistics="Same LCB bar as the stake rule; n = 4 today for bank_at_+20pct (LCB -10.5 pts).",
  incentives="Promotion is by evidence.", evidence="Live scorecard.", ruling="Uphold.", amendment="None.",
  growth_cost="None.", ruin_reduction="None.", interactions="None.", next_review="2026-11-26"),
dict(
  id="bandit-1h-entry-cap", title="BANDIT entry gate: skip a coin up more than +30% in the hour before entry (provisional trial)",
  status="in_force", status_after="in_force", verdict="amend", needs_david=False, ruling_date="2026-10-07",
  purpose="Stops BANDIT buying a meme coin right after its vertical candle. All three closed clips entered above +30% 1h (goon, Agency, SHARTCOIN) lost money and sat 14-28% under entry at the 4h mark.",
  mechanism="`meme_4h_momentum_clip` entry gate: the 1h price-change ceiling drops from +200% to +30%, so a coin up more than +30% over the hour before entry is skipped. Every other gate is unchanged (liquidity >= $100k, age < 14d, 1h >= +5%, 6h >= +10%, 1h volume >= $25k, buy share >= 52%, 5m > -8%, 24h > -40%, quote impact < 1%), and so is sizing (`steward_sizing_guidance`, results-driven). The gate is applied in BANDIT's runtime scan on the box (`/workspace/bandit/_scan_https_once.py`, fail text `1h_cap_30 trial`); it isn't in versioned repo code or SQL. Every coin the cap blocks is logged as a pass with `steward_log_decision` (decision `skip`, `blocked_by = '1h_cap_30'`), so `pass_marks.py` scores it at its 4h mark like any other pass. Sunset check: `decision_candidates` where steward = 'bandit' and `meta->>'blocked_by' = '1h_cap_30'` (first pass per mint; 4h return = counterfactual_pnl / book_price) against `trade_outcomes` for thesis `meme_4h_momentum_clip` opened after this rule's `desk_rules.created_at` (realized_pnl / cost; SHARTCOIN, opened 2026-10-07 16:29 PT, is the last clip before the cap).",
  paths=["supabase/schemas/64_bandit_1h_entry_cap.sql", "stewards/bandit/README.md"],
  growth="The cap blocks about 20% of entries (3 of 15 closed clips), and historically all three were losers: -0.1156 SOL combined, -21.0% mean realized and -20.8% mean 4h-mark return. No winner had a 1h move above +11.3% at entry (familiars), so the upside cost in the record is nil. Applied to history, the 15 clips go from +0.0700 SOL to +0.1856 SOL. The cost to watch is pace: learning speed is trade count, and of the four clips that pass every current gate with data (SHARTCOIN, Agency, GTA6, X7), two would now be blocked, so under today's gates the cap could remove more than 20% of entries. The sunset check measures that cost directly.",
  ruin="A filter can only remove entries. It can't raise the size of any clip or the loss on one. Sizing, the 10% exposure budget (memes at full notional, about one clip at a time) and drawdown scaling are untouched, so P(DD50) and P(book < 20%) can't rise; at worst they're unchanged. It doesn't address the tail that actually hurt: the two -100% rugs (ACAT, 1h +3.8%; GTA6, 1h ~+10%) entered well under the cap.",
  statistics="Three clips decide it. If 3 of the 15 clips were dropped at random, the chance all three are losers (9 losers of 15) is C(9,3)/C(15,3) = 84/455 = 0.185, so this is weak evidence for a rule with a clear mechanism, not a proven edge. Two of the three (Agency, SHARTCOIN) are the two latest losses, the ones the rule was written after. The 1h values for goon and Agency were rebuilt from GeckoTerminal 5m candles, not read from a scan; on the five clips that have both, the rebuild was within about 0.4-6 points of the scan value. Any cap between about +12% and +52% sorts history the same way; +30% is a round number inside that gap, not tuned to its edge. Regimes changed during the sample (old half-at-+50% exits on GROK and JEANPHIL; QUEEF and TIGRINO sold hours after their 4h stop), and 11 of 15 clips would fail at least one of today's gates anyway, so history says little about the current gate set. Hence a trial with a preset sunset, not a permanent rule.",
  incentives="Preregistered: the rule was written down in BANDIT's study before the next coin and checked against all 15 closed clips, not only the last loss. Blocked coins must be logged as passes (`steward_log_decision`, `blocked_by = '1h_cap_30'`), at least every coin that cleared every other gate, so BANDIT's 4h pass marks score them and the cap is judged on what it gave up as well as what it avoided. A steward that skipped the logging could make the cap look free; unlogged blocks make the trial unreadable. Waiting for the 1h move to cool and re-scanning later is allowed; that's a new decision, scored on its own. Interacts with nothing in sizing; it only changes which coins reach `steward_sizing_guidance`.",
  evidence="BANDIT's entry-filter study (`/workspace/bandit/research/entry_filter_study.md` and `.csv` on the box, built by `build_study.py` / `evaluate_rules.py` from ledger reads; 2026-10-07). 15 closed clips. Entered above +30% 1h: goon +52.4% (-0.0564 SOL, -12.5%), Agency +63.0% (-0.0313 SOL, -26.3%), SHARTCOIN +59.5% (-0.0278 SOL, -24.2%); all three lost, -0.1156 SOL combined, about -21% at the 4h mark. At or under +30%: 11 clips, +0.4616 SOL, 6 winners (JEANPHIL, QUEEF, GROK, familiars, TIGRINO, FEELSGOOD), none with a 1h move above +11.3%. X7 (-0.2760 SOL) has no usable entry-time 1h value and counts as kept. All 15: +0.0700 SOL; with the cap: +0.1856 SOL. Rejected runner-up, 'at most half of the 6h move came in the last hour' (ln(1+1h)/ln(1+6h) <= 0.5): it would drop familiars (+0.264 SOL, banked at +50%) and keep goon (a loser), costing +0.205 SOL net, and it is undefined for 4 of 15 clips where the 6h change was <= 0. Also rejected: 5m > 0 (drops TIGRINO, JEANPHIL and QUEEF), buy share >= 55% (data on 5 clips, signal looks inverted), max age 7d (n = 1), liquidity >= $150k (no separation).",
  ruling="Uphold as a provisional trial, amended from the +200% ceiling to +30%. Sizing stays results-driven. Not a risk-budget tradeoff, so not for David. Sunset: review after 10 blocked passes (blocked_by '1h_cap_30') or 10 new clips, whichever comes first. Compare the blocked coins' mean 4h return against the taken clips' mean realized return over the same period. If the blocked coins beat the taken clips, strike the cap.",
  amendment="BANDIT's 1h price-change ceiling: +200% -> +30% (skip a coin whose 1h change at scan time is above +30%). Every blocked coin is logged as a pass with blocked_by '1h_cap_30'. All other gates and sizing unchanged.",
  growth_cost="About 20% of historical entries blocked, all losers (-0.1156 SOL); zero historical winners lost. Clip pace may fall more than 20% under today's gates (2 of 4 clips that pass every current gate would be blocked).", ruin_reduction="None claimed: a filter can't raise loss, and it doesn't catch the -100% rugs (ACAT, GTA6). Removes the -21% average post-vertical-candle entry.",
  interactions="portfolio-exposure (one clip at a time, so a blocked coin frees the slot for the next candidate), starter-stake, drawdown-scaling, shadow-exits (exit rules are separate; goon touched +25.9% before bleeding).",
  next_review="after 10 blocked passes (blocked_by 1h_cap_30) or 10 new clips, whichever comes first"),
]
