"""Single source for the desk rulebook: docs/rules/<id>.md and the public.desk_rules seed.
Numbers come from tools/court (sim.py, grid*.py, replay.py) on the 2026-09-26 ledger.
MC = Monte Carlo, one year at ledger pace (QUANTANAMO 100, ODDSBORNE 150, BANDIT 400 trades),
returns bootstrapped from each steward's real trade_outcomes, re-centred to a true Sharpe/trade.
P(DD50) = chance of a >= 50% peak-to-trough drawdown within the year; ruin = book < 20% of start."""

RULING_DATE = "2026-09-26"

RULES = [
dict(
  id="edge-max-stake", title="Edge-scaled max stake (proven-edge growth)",
  status="in_force", status_after="in_force", verdict="amend", needs_david=False,
  purpose="Stops an unbounded requested size (the $200 Miami bet on a $490 book) while letting a proven edge compound.",
  mechanism="`private.edge_max_stake`: unproven (n < 10 or LCB <= 0) gets the starter; proven gets max(starter, min(book x 0.5 x LCB / sd^2, starter x 2^(1 + (n - 10) / 5))). LCB = mean - sd/sqrt(n) of return on stake. `sized_notional = min(requested, max_stake, cash)`.",
  paths=["supabase/schemas/22_edge_scaled_stake.sql", "supabase/schemas/23_edge_stake_reason.sql", "supabase/schemas/37_court_rulings.sql", "supabase/schemas/38_edge_max_stake_null_thesis.sql"],
  growth="Once proven, the cap is half-Kelly on the lower bound, which is the growth-optimal size under parameter uncertainty (full Kelly on a noisy mean overbets). The doubling-per-5-trades brake lets a real edge reach ~40% of book by n = 20. At Sharpe 0.2/trade the proposed rules reach a median 28x (BANDIT) and 8x (ODDSBORNE) in a year.",
  ruin="Without it, size is whatever the steward requests. ODDSBORNE's 40%-of-book loss on 2026-09-20 is the case it prevents. Half-Kelly on LCB never bets more than half the edge-optimal fraction.",
  statistics="The 1-sigma LCB with continuous monitoring falsely marks a zero-edge thesis proven in 47-69% of MC paths within a year. A 2-sigma bound cuts that to 9-23%, but it delays real proof (QUANTANAMO at Sharpe 0.2: 14 -> 38 trades) and cuts BANDIT's median growth at Sharpe 0.2 from 28.4x to 9.8x. With drawdown scaling as the backstop, false proofs cost little: P(DD50) at zero edge is 9.3% at 1 sigma vs 4.7% at 2 sigma.",
  incentives="A steward could inflate `requested` to get more size. That no longer helps: the cap binds, and the multiplier that rewarded inflation is struck (see confidence-multiplier). Only closed, priced, non-paper trades count, so the n gate can't be padded with paper trades.",
  evidence="MC grid (tools/court/grid.json, grid2.json). Live: every thesis is unproven today (max n = 6 per thesis; BANDIT has 35 at steward level with LCB -7.4%).",
  ruling="Uphold the proven-edge formula at 1 sigma. Amend so n and the moments include discounted backtest evidence (backtest-evidence-credit) and so the cap is multiplied by the steward drawdown scale instead of per-thesis loss halving.",
  amendment="n_eff = n_live + min(0.5 x n_backtest, 20), with the backtest mean haircut 50%. The cap is multiplied by the scale from `private.steward_drawdown`. The starter is a share of current book.",
  growth_cost="None vs current; raises growth (loss halving removed).", ruin_reduction="Bounds every entry; half-Kelly on LCB.",
  interactions="starter-stake, drawdown-scaling, backtest-evidence-credit, confidence-multiplier, entry-cap-snapshot.",
  next_review="2026-10-26"),
dict(
  id="starter-stake", title="Starter stake for unproven theses (equal 3% book risk per bet)",
  status="in_force", status_after="in_force", verdict="amend", needs_david=False,
  purpose="Lets an unproven thesis trade (learning comes from trade count, not size) without a big loss before there is evidence.",
  mechanism="starter = 0.03 x current book / steward bet volatility (`private.steward_bet_vol`: sd of return on stake over the steward's closed priced non-paper trades, floored at 0.25; 1.0 while n < 5), x the steward drawdown scale. On 2026-09-26: QUANTANAMO sd 0.222 -> floor 0.25 -> 12% of book = $660; BANDIT sd 0.449 -> 6.68% = 0.1205 SOL (x0.987 = 0.119); ODDSBORNE sd 1.957 -> 1.53% = $4.24 (x0.5 = $2.12). History: fixed dollars ($250 / $15 / 0.10 SOL) until migration 37, then the same as a book share until migration 41.",
  paths=["supabase/schemas/22_edge_scaled_stake.sql", "supabase/schemas/37_court_rulings.sql", "supabase/schemas/41_court_decisions.sql"],
  growth="A fixed-dollar starter never compounds: after a 2x the starter is 2.5% of book, not 5%. A book-share starter keeps pace with the book. The starter LEVEL is the bigger growth question. A flat ~5% of book is a very different risk per steward: book volatility per unproven trade is ~1.25% for QUANTANAMO (stocks with stops, sd of return on stake 0.22-0.25), 2.5% for BANDIT (sd 0.45) and 10.6% for ODDSBORNE (binary, sd 1.96).",
  ruin="Fixed dollars get riskier as the book shrinks. MC at zero edge: ODDSBORNE ruin 10.1% with the fixed $15, 0.1% with a book share.",
  statistics="The starter should be calibrated to stake volatility, not a flat %. A vol-normalized starter, stake = v x book / sd(return on stake), gives every steward the same book risk per unproven bet.",
  incentives="With a flat %, the steward whose instruments are most volatile gets the most book risk per bet (ODDSBORNE). Vol-normalizing removes that tilt.",
  evidence="MC (grid2.json): QUANTANAMO at Sharpe 0.1/0.2, P(2x in a year) is 10.7%/44.7% at today's starter vs 18.5%/55.6% at v = 4% (16% of book), with P(DD50) <= 0.3% either way (<= 1.5% with a 5% chance of a -40% gap per trade). ODDSBORNE at zero edge: P(DD50) 50.8% at today's 5.4% vs 1.1% at v = 4% (2.0% of book).",
  ruling="Amend (shipped in two steps): book share, not fixed dollars (37); level set to equal risk per bet at v = 3% (41, decided 2026-09-26 by the parent agent under David's delegation). The 0.25 sd floor stops a lucky low-variance sample from inflating the starter (max starter 12% of book).",
  amendment="starter = 0.03 x book / max(steward sd of return on stake, 0.25) (1.0 while the steward has < 5 trades), x drawdown scale. Proven theses keep half-Kelly on the LCB, never below the starter.",
  growth_cost="Negative for QUANTANAMO ($250 -> $660: MC P(2x) at Sharpe 0.2 rises from 44.7% toward the v = 3-4% range); ODDSBORNE smaller ($15 -> $4.24 before scale).", ruin_reduction="ODDSBORNE zero-edge P(DD50) 50.8% at 5.4% of book vs ~1-2% at v = 3-4%; QUANTANAMO P(DD50) stays <= 1.5% with gap stress.",
  interactions="edge-max-stake, drawdown-scaling.",
  next_review="2026-10-10"),
dict(
  id="loss-streak-halving", title="Per-thesis consecutive-loss halving (x0.5 per loss, floor x0.25)",
  status="in_force", status_after="repealed", verdict="strike", needs_david=False,
  purpose="Meant to cut size when a thesis is failing.",
  mechanism="`private.edge_max_stake` multiplied the cap by 0.5^min(loss_streak, 2).",
  paths=["supabase/schemas/23_edge_stake_reason.sql", "supabase/schemas/37_court_rulings.sql"],
  growth="It cuts size right after losses, regardless of edge. Under the same starter, MC growth with halving vs drawdown scaling: BANDIT at Sharpe 0.1 median 1.74x vs 1.98x, P(2x) 52.5% vs 62.9%; at Sharpe 0.2 17.8x vs 28.4x. QUANTANAMO at Sharpe 0.2: P(2x) 33% vs 44.7%.",
  ruin="Drawdown scaling gives the same or better ruin protection: BANDIT P(DD50) 12.5% (halving) vs 9.9% (drawdown) at Sharpe 0.1, and 11.3% vs 9.3% at zero edge. For ODDSBORNE at a 5.4% starter, halving has the lower P(DD50) (42% vs 51% at zero edge), but only because it shrinks an oversized starter. A correctly sized ODDSBORNE starter makes both ~0%.",
  statistics="Loss streaks carry no information: BANDIT P(loss | previous loss) 0.53 vs P(loss) 0.51, lag-1 autocorrelation 0.004 over 35 trades. The edge estimate (LCB) already absorbs the losses. Halving punishes the same evidence twice.",
  incentives="It's per thesis, so a steward escapes it by registering a new thesis (the new-thesis escape). It also rewards cutting a loser early to reset the streak, whatever the thesis's real invalidation says.",
  evidence="Ledger autocorrelation (tools/court). MC grid2 book5_halving vs book5_ddscale. Replay of real sequences (replay.json): BANDIT +2.6% with halving vs -0.7% with the proposed rules, on one 35-trade path. That's inside noise; the MC is the evidence.",
  ruling="Strike. Replace with steward-level drawdown scaling (drawdown-scaling).",
  amendment="Removed from `private.edge_max_stake`. `loss_streak` stays in the stats for information.",
  growth_cost="Removing it raises growth (BANDIT median +14% at Sharpe 0.1).", ruin_reduction="Replaced by drawdown scaling, which has equal or lower P(DD50) at the same starter.",
  interactions="drawdown-scaling, new-thesis-escape.",
  next_review="2026-12-26"),
dict(
  id="drawdown-scaling", title="Steward-level drawdown scaling",
  status="proposed", status_after="in_force", verdict="amend", needs_david=False,
  purpose="Cuts risk when the BOOK is in trouble (the thing that can actually be ruined), not when one thesis label had a streak.",
  mechanism="scale = 1.0 at <= 10% below the steward's closing high-water mark, falling linearly to 0.5 at >= 40%. The HWM is the max of each UTC day's last book observation, used because intraday entry-time snapshots include double-count artifacts. It multiplies every thesis's cap, proven or not. `private.steward_drawdown`.",
  paths=["supabase/schemas/37_court_rulings.sql"],
  growth="No cost in normal noise (<= 10%). The floor of 0.5 keeps a recovering book trading at half size, so recovery isn't choked. MC growth equals or beats halving everywhere at the same starter.",
  ruin="Anti-martingale at the book level: sizes shrink as the book approaches ruin. BANDIT MC at zero edge: P(DD50) 35.9% with no control vs 9.3% with drawdown scaling; ODDSBORNE ruin 7.4% vs 0.1%.",
  statistics="Uses the book path, which is the actual ruin variable. No thesis-level noise. The 10% dead band sits above normal noise (QUANTANAMO's worst close-to-close drawdown is 16%; BANDIT's intraday swings reach 30%).",
  incentives="Steward-wide, so it can't be escaped with a new thesis. Deposits would reset the HWM mechanics; none have happened. A deposit should be recorded as a flow before this rule reads it.",
  evidence="Live on 2026-09-26: QUANTANAMO HWM $6,098.56 -> 9.8% below -> x1.00; ODDSBORNE HWM $524.76 -> 47.2% below -> x0.50; BANDIT HWM 2.0207 SOL -> 10.8% below -> x0.987.",
  ruling="Enact.", amendment="New rule (migration 37).",
  growth_cost="0 inside a 10% drawdown; x0.5 at worst.", ruin_reduction="BANDIT P(DD50) 35.9% -> 9.3%; ODDSBORNE ruin 7.4% -> 0.1% (zero edge).",
  interactions="Replaces loss-streak-halving; closes new-thesis-escape; multiplies edge-max-stake.",
  next_review="2026-10-26"),
dict(
  id="new-thesis-escape", title="New-thesis escape from a loss-reduced cap",
  status="in_force", status_after="repealed", verdict="strike", needs_david=False,
  purpose="The problem: per-thesis halving could be escaped by registering a new thesis. The first fix (steward-wide cap on every unproven thesis, #97) pinned QUANTANAMO themes at $62.50 and was reverted (#98).",
  mechanism="Resolved structurally. Loss halving is struck, and the only loss response is steward-wide drawdown scaling, which applies to every thesis, new or old. A new thesis gets the starter x the steward's drawdown scale, the same as any unproven thesis.",
  paths=["supabase/schemas/34_revert_steward_wide_starter.sql", "supabase/schemas/37_court_rulings.sql", "supabase/schemas/41_court_decisions.sql"],
  growth="#97's rule cut QUANTANAMO's unproven themes 75% ($250 -> $62.50) because of 3 losses on another thesis. That's a large growth cost with no ruin case: loss streaks don't predict (see loss-streak-halving). The structural fix costs nothing.",
  ruin="Covered by drawdown scaling at the book level.",
  statistics="Punishing unrelated theses for one thesis's streak treats noise as signal.",
  incentives="The remaining gap (a new QUANTANAMO thesis stated at >= 80 passed the gate with zero evidence) is closed by migration 41: the gate reads only the results score, and a thesis with < 3 effective trades is unscored and needs David. See quantanamo-80-gate.",
  evidence="#97 live numbers: every unproven QUANTANAMO theme at $62.50; reverted by #98 (migration 34).",
  ruling="Strike the problem at its root (no per-thesis punishment exists to escape). No separate rule needed.",
  amendment="None beyond loss-streak-halving and drawdown-scaling.",
  growth_cost="None.", ruin_reduction="Via drawdown-scaling.",
  interactions="loss-streak-halving, drawdown-scaling, quantanamo-80-gate.",
  next_review="2026-10-26"),
dict(
  id="confidence-multiplier", title="Half-Kelly outcome multiplier on the requested size",
  status="in_force", status_after="repealed", verdict="strike", needs_david=False,
  purpose="Scaled requested size by a half-Kelly estimate from hit rate and avg win/loss (0.5 when n < 5, 0.25 with no edge).",
  mechanism="`sized_notional = min(requested x multiplier, max_stake, cash)`. Now `min(requested, max_stake, cash)`. The multiplier is still returned for information.",
  paths=["supabase/schemas/11_outcome_rescore_sizing.sql", "supabase/schemas/22_edge_scaled_stake.sql", "supabase/schemas/37_court_rulings.sql"],
  growth="It halves an honest steward's size on every unproven thesis (n < 5 -> 0.5), on top of the starter that already exists for that.",
  ruin="Adds nothing: max_stake already bounds every entry, with a proper lower-bound edge estimate.",
  statistics="It uses raw hit rate and payoff with no shrinkage. At n = 5 a hit-rate estimate is +/- 22 points (1 sigma), so the multiplier is noise until n ~ 30, and the edge-scaled cap already handles small samples properly.",
  incentives="Directly gameable: request 2x to get 1x. An honest steward is penalized, and a gaming one isn't.",
  evidence="Structural. BANDIT's 0.45 SOL clip x 0.5 = 0.225 was already capped by max_stake. The multiplier changed nothing for a steward requesting above the cap.",
  ruling="Strike from sizing. Keep reporting it.",
  amendment="guidance: sized_notional = min(requested, max_stake, spendable cash). QUANTANAMO requested % is no longer multiplied (scheduled-run prompt). The retired workers/research mirror is left alone.",
  growth_cost="Raises honest sizes up to 2x (never above max_stake).", ruin_reduction="None lost (max_stake binds).",
  interactions="edge-max-stake.",
  next_review="2026-12-26"),
dict(
  id="outcome-rescore-confidence", title="Results re-score of thesis confidence (expected return per trade)",
  status="in_force", status_after="in_force", verdict="amend", needs_david=False,
  purpose="Tempers a steward's stated confidence with realized outcomes. Feeds the QUANTANAMO >= 80 gate and hardening/forming status.",
  mechanism="`private.thesis_results_score`: n_eff = live trades + min(0.5 x backtest n, 20); mean_eff pools the live mean return on stake with the backtest mean haircut 50%; sd_eff = max(pooled sd, 0.25); results_confidence = round(100 x Phi(mean_eff / (sd_eff / sqrt(n_eff)))) when n_eff >= 3, else null (unscored). Demote hardening -> forming only when the live upper bound mean + max(sd, 0.25)/sqrt(n) < 0, or n >= 10 with mean < 0; kill only when n >= 10 and the upper bound < 0. theses.confidence (display) = results_confidence when scored, else the stated number. Only the re-score writes the results columns (guard trigger). Was: Beta on hit rate, cap 60 and demote at n >= 5 with negative P/L.",
  paths=["supabase/schemas/11_outcome_rescore_sizing.sql", "supabase/schemas/41_court_decisions.sql"],
  growth="Hit rate isn't edge. QUANTANAMO's style wins big and loses small (winners avg +30% of stake, losers -11%; breakeven hit rate 27%). A thesis hitting 35% at that payoff earns ~+3.2% per trade, but its confidence converges to 35 and it can never pass the 80 gate. The 5-trade demotion blocks 41% of genuinely good theses (true Sharpe 0.1/trade) and 33% at Sharpe 0.2.",
  ruin="Small: bad theses are already small via max_stake, and demotion only affects QUANTANAMO autonomy.",
  statistics="Five trades can't tell a Sharpe-0.1 thesis from zero: P(sum < 0) = Phi(-0.1 sqrt 5) = 41%. A hit-rate Beta prior ignores payoff asymmetry.",
  incentives="Pushes a steward toward high-hit-rate, low-payoff trades (take profits early, let losers run) just to keep confidence high: the opposite of what compounds.",
  evidence="Closed-form above; ledger payoff stats (QUANTANAMO 7 trades: hit 29%, payoff ratio 2.7).",
  ruling="Amend (shipped in migration 41; decided 2026-09-26 by the parent agent under David's delegation). Status changes on the 2026-09-26 re-run: none (no thesis has a negative upper bound or n >= 10).",
  amendment="Score on expected return per trade (above). Stated confidence is display only.",
  growth_cost="Removes the permanent block on asymmetric theses.", ruin_reduction="Demotion/kill now needs real evidence of negative edge.",
  interactions="quantanamo-80-gate, edge-max-stake, backtest-evidence-credit.",
  next_review="2026-10-26"),
dict(
  id="quantanamo-80-gate", title="QUANTANAMO autonomous-entry gate: hardening thesis with results score >= 80",
  status="in_force", status_after="in_force", verdict="amend", needs_david=False,
  purpose="David approves anything below 80; autonomy only for strong theses.",
  mechanism="`steward_sizing_guidance`: QUANTANAMO entry_allowed needs status = hardening and theses.results_confidence >= 80 (reason `quantanamo_unscored` when unscored, else `quantanamo_confidence_gate`). Backtest credit maps to a score through the same math: a thesis with only backtest evidence has n_eff = min(0.5 x n_bt, 20) (>= 3 needs n_bt >= 6) and scores Phi(0.5 x mean_bt / (max(sd_bt, 0.25) / sqrt(n_eff))); passing 80 needs z >= 0.84, e.g. at full weight (n_bt >= 40) and sd 0.25 a backtest mean >= 9.4% per trade.",
  paths=["supabase/schemas/22_edge_scaled_stake.sql", "supabase/schemas/41_court_decisions.sql", "docs/scheduled-run-prompt.md"],
  growth="Today 2 of 12 live theses pass (neocloud_compute 85, semis_photonics 85). Because confidence is a hit-rate posterior, asymmetric-payoff theses can't reach 80 from results (see outcome-rescore-confidence).",
  ruin="Keeps autonomy away from theses with little conviction. The size risk is already bounded by max_stake.",
  statistics="Before 41, at n = 0 the gate read the steward's self-stated number (80 was a claim, not a measurement). Now 80 means P(expected return per trade > 0) >= 0.8 on at least 3 effective trades (z >= 0.84, close to the 1-sigma LCB > 0 that proves an edge for sizing).",
  incentives="Before 41 a steward could state 85 on a brand-new thesis and pass, and couldn't earn 80 with an asymmetric winner. Now stated numbers can't open the gate, the results columns are write-protected (only the re-score writes them), and an asymmetric winner earns its score from expectancy.",
  evidence="Live theses 2026-09-26.",
  ruling="Amend (shipped in migration 41; decided 2026-09-26 by the parent agent under David's delegation): the 80 threshold stays, but it reads the results score only. On 2026-09-26 no thesis passes: neocloud_compute (1 trade) and semis_photonics (0) are unscored, earnings_gap_structure scores 56; every QUANTANAMO entry needs David until a thesis earns >= 80 or gets qualifying backtest credit.",
  amendment="Gate on results_confidence >= 80; unscored (< 3 effective trades) fails and asks David; stated confidence is display only.",
  growth_cost="Autonomy now waits for evidence (David approves meanwhile).", ruin_reduction="Closes the self-stated-85 path to autonomy.",
  interactions="outcome-rescore-confidence, new-thesis-escape, backtest-evidence-credit.",
  next_review="2026-10-26"),
dict(
  id="required-invalidation", title="Required invalidation on entry (guidance + table trigger)",
  status="in_force", status_after="in_force", verdict="uphold", needs_david=False,
  purpose="Every lot has a written, priced falsifier before money goes in, so exits aren't improvised.",
  mechanism="Guidance returns missing_invalidation without p_invalidation_price > 0. `private.require_lot_invalidation` rejects a new or re-opened open lot without one.",
  paths=["supabase/schemas/22_edge_scaled_stake.sql"],
  growth="No cost: any trade can state an invalidation. It's also the input a risk-based starter would need.",
  ruin="Prevents open-ended holds of broken trades. BANDIT's -100% rugs (GTA6, ACAT) show a stop doesn't cap loss in illiquid coins. That's handled by stake size, not by this rule.",
  statistics="n/a (process rule).",
  incentives="A steward could set an absurdly far invalidation. Guidance only checks > 0, and the ODDSBORNE script checks 0 < inval < price. Follow-up: pass the entry price to guidance so it can reject inval >= entry for longs.",
  evidence="All open lots carry one (watchdog v_open_lots_missing_invalidation = 0).",
  ruling="Uphold.", amendment="Follow-up (not shipped): entry-price sanity check.",
  growth_cost="None.", ruin_reduction="Moderate (process).",
  interactions="regular-session-invalidation, starter-stake.", next_review="2027-03-26"),
dict(
  id="regular-session-invalidation", title="Equity invalidation exits fire only on regular-session prints",
  status="in_force", status_after="in_force", verdict="uphold", needs_david=False,
  purpose="Avoid full-lot exits on thin pre/after-hours prints; those set review_at_open instead.",
  mechanism="Monitor policy autonomous-position-v5, `private.is_us_regular_session` with the NYSE holiday/early-close calendar. Coins and PM are 24/7, with no session filter.",
  paths=["workers/research/src/position-decision.ts", "supabase/schemas/29_us_market_calendar.sql", "packages/contracts/src/market-calendar.ts"],
  growth="Avoids selling a good lot on a spurious extended-hours print (CODA trades thin).",
  ruin="Small cost: a real overnight break is acted on at the open, and the review flag makes sure it is. Market orders can't fill after hours anyway (broker is RTH-only).",
  statistics="Extended-hours prints are few, wide-spread trades; a single print isn't a price.",
  incentives="None.", evidence="Structural.", ruling="Uphold.", amendment="None.",
  growth_cost="None.", ruin_reduction="Neutral.", interactions="required-invalidation.", next_review="2027-03-26"),
dict(
  id="stale-book-6h", title="Entries need a book observation <= 6 hours old",
  status="in_force", status_after="in_force", verdict="uphold", needs_david=False,
  purpose="Sizing uses the real book and cash, not a stale snapshot (a stale high book would oversize).",
  mechanism="Guidance returns stale_book when the older of the equity and cash observations is > 360 minutes old.",
  paths=["supabase/schemas/22_edge_scaled_stake.sql"],
  growth="Near zero: the steward records a fresh snapshot before trading (one call).",
  ruin="Prevents sizing off a book that already fell.", statistics="n/a.",
  incentives="None; the fix is one snapshot write.", evidence="Structural.", ruling="Uphold.", amendment="None.",
  growth_cost="~0.", ruin_reduction="Small-moderate.", interactions="starter-stake, drawdown-scaling (both read the book).", next_review="2027-03-26"),
dict(
  id="thesis-status-blocks", title="Killed, rejected or unknown thesis blocks new entries",
  status="in_force", status_after="in_force", verdict="uphold", needs_david=False,
  purpose="A falsified or rejected idea (or a typo'd id) can't size an entry.",
  mechanism="Guidance: unknown_thesis, thesis_rejected, thesis_killed; sized_notional = 0.",
  paths=["supabase/schemas/21_unknown_thesis_gate.sql", "supabase/schemas/22_edge_scaled_stake.sql"],
  growth="None: a killed thesis has no edge by definition.", ruin="Stops trading a falsified idea.",
  statistics="n/a.", incentives="Can't be escaped by tagging with a non-existent id.",
  evidence="Structural.", ruling="Uphold.", amendment="None.",
  growth_cost="None.", ruin_reduction="Moderate.", interactions="new-thesis-escape.", next_review="2027-03-26"),
dict(
  id="cash-only-no-margin", title="Cash only: no margin, no leverage",
  status="in_force", status_after="in_force", verdict="uphold", needs_david=False,
  purpose="Worst case is losing the stakes. The book can't go negative or be force-liquidated.",
  mechanism="sized_notional <= spendable cash (min(cash, buying power)); the broker rejects buys needing margin.",
  paths=["supabase/schemas/14_no_position_cap.sql", "workers/broker/src/robinhood-broker-agent.ts"],
  growth="Caps total exposure at 1x book. For a proven edge, half-Kelly on LCB rarely asks for more than 1x in these books.",
  ruin="Removes the one path to losing more than the book.", statistics="n/a.",
  incentives="None.", evidence="Standing preference (David).", ruling="Uphold.", amendment="None.",
  growth_cost="Small.", ruin_reduction="Large (eliminates negative-equity paths).", interactions="portfolio-exposure.", next_review="2027-03-26"),
dict(
  id="listed-equity-registry", title="Listed-equity registry exempts real tickers from the ontology junk filter",
  status="in_force", status_after="in_force", verdict="uphold", needs_david=False,
  purpose="Real tickers (TXN, GFS, MP) aren't discarded as junk words.",
  mechanism="`public.listed_equities`, checked by `private.ontology_label_is_junk` / `isJunkOntologyLabel`.",
  paths=["supabase/schemas/26_listed_equities.sql"],
  growth="Unblocked 35 tickers and 58 candidates.", ruin="None.", statistics="n/a.",
  incentives="Only verified listings are added.", evidence="2026-09-26 sweep: 35 tickers, 58 candidates restored.", ruling="Uphold.", amendment="None.",
  growth_cost="Negative (helps).", ruin_reduction="None.", interactions="None.", next_review="2027-03-26"),
dict(
  id="entry-cap-snapshot", title="Cap-at-entry snapshot and ledger watchdog",
  status="in_force", status_after="in_force", verdict="uphold", needs_david=False,
  purpose="Every entry is audited against the cap in force when it was made. Breaches and missing invalidations surface twice a day.",
  mechanism="`max_stake_at_entry` trigger; `v_ledger_integrity` (entry_over_max_stake at > 1.10x); `v_invalidation_breaches`; `v_open_lots_missing_invalidation`; `v_ledger_watchdog`.",
  paths=["supabase/schemas/24_ledger_watchdog.sql", "supabase/schemas/30_max_stake_at_entry.sql"],
  growth="None (measurement).", ruin="Catches rule bypasses.", statistics="n/a.",
  incentives="Makes bypass visible.", evidence="Live counts in the health routine.", ruling="Uphold.", amendment="None.",
  growth_cost="None.", ruin_reduction="Detective.", interactions="edge-max-stake.", next_review="2027-03-26"),
dict(
  id="backtest-evidence-credit", title="Out-of-sample backtest evidence counts toward proven edge",
  status="proposed", status_after="in_force", verdict="amend", needs_david=False,
  purpose="Caps shouldn't wait for 10 live trades when a thesis has real out-of-sample evidence.",
  mechanism="`public.thesis_backtest_evidence` (one active row per thesis; out_of_sample and costs_included required; linked to a `strategy_tests` row with status survived and deflated Sharpe > 0). It adds min(0.5 x n, 20) effective trades, with its mean return haircut 50%, to the thesis's live moments in `private.edge_max_stake`.",
  paths=["supabase/schemas/37_court_rulings.sql", "supabase/schemas/38_edge_max_stake_null_thesis.sql"],
  growth="Faster proof when the edge is real: BANDIT at Sharpe 0.2 is proven in 7 trades vs 13; QUANTANAMO 11 vs 14.",
  ruin="Low. An overfit backtest showing a fake +0.2 Sharpe proves a zero-edge thesis early (6-7 trades), but P(DD50) moves only 9.3% -> 9.7% (BANDIT) because of the haircut, the 20-trade limit, LCB-Kelly and drawdown scaling. Live losses quickly outweigh the credit.",
  statistics="Weight 0.5 and a 50% mean haircut are standard discounts for backtest optimism (selection and overfitting). Only out-of-sample, cost-inclusive results from a surviving strategy test with deflated Sharpe > 0 count.",
  incentives="A steward could cherry-pick a backtest. That's mitigated by requiring out_of_sample = true, a linked surviving strategy_tests row, the haircut and the limit, and the rows are auditable on the desk.",
  evidence="MC grid2 backtest runs (bt30_w.5_h.5).",
  ruling="Enact with conservative parameters.", amendment="New rule (migration 37).",
  growth_cost="Negative (speeds proof).", ruin_reduction="Neutral-slightly negative (quantified above).",
  interactions="edge-max-stake, outcome-rescore-confidence.", next_review="2026-11-26"),
dict(
  id="portfolio-exposure", title="Portfolio exposure: open risk <= 10% of book (gap-prone lots at full notional)",
  status="proposed", status_after="in_force", verdict="amend", needs_david=False,
  purpose="Per-entry caps don't bound total or correlated exposure across open lots, and an invalidation line doesn't bound a lot that can gap straight through it.",
  mechanism="`private.open_risk_lots()` (per lot, `public.v_exposure_lots`) summed by `private.steward_open_risk` (`public.v_exposure_usage`), in the book unit, `risk_basis` per book. QUANTANAMO equities `to_invalidation`: qty x max(mark - invalidation_price, 0) (no invalidation: qty x mark; unmarked: 0, flagged). ODDSBORNE binaries and BANDIT memes `full_notional`: every open binary at price x contracts (mark, else average cost) and every meme lot at its full cost basis (qty x average cost, else qty x mark). Budget 10% of book. Guidance sizes a new entry to fit: min(requested, max_stake, cash, headroom / risk fraction), where the fraction is 1 for full_notional books and (entry - invalidation) / entry for equities (1 without p_entry_price); no headroom -> `exposure_cap`. Guidance, v_exposure_usage and the v_ledger_watchdog `exposure` summary carry `risk_basis`.",
  paths=["supabase/schemas/41_court_decisions.sql", "supabase/schemas/44_exposure_gap_full_notional.sql"],
  growth="Any cap here limits concentration into the best ideas. Full notional on the gap-prone books makes BANDIT effectively one clip at a time (budget 0.180 SOL vs a 0.119 starter: one clip leaves 0.061 SOL of headroom) and lets ODDSBORNE hold about 13 of today's $2.12 tickets ($27.69 budget).",
  ruin="Gap risk is the real tail. A Polymarket binary goes from its mark to 0 on one score, and a meme can rug in one block, so the -40% meme line and the outcome-price line on a binary bound nothing; counting them to invalidation understated BANDIT's risk per clip by 60% (0.4 x notional vs the whole notional). Equities keep to-invalidation, since a stop on a listed name usually fills near its line (gaps excepted). QUANTANAMO on 2026-09-26 (9/25 after-hours marks, lines raised at 3:08 PM PT): NBIS $80, CIFR $79, CODA $193 = $351 (6.4% of $5,501). Before the raise: NBIS $161, CIFR $186, CODA $308 = $654 (11.9%, over budget).",
  statistics="Needs a correlation estimate by theme; with n this small, use theme membership as the proxy. For binaries and memes the loss distribution is bimodal (full loss or not), so the right risk unit is the notional, not a distance to a line.",
  incentives="Without it, a steward can stack correlated starters across several theses. To-invalidation on a gap-prone lot rewards writing a tight line the venue can't honor; full notional removes that lever.",
  evidence="Open position_episodes, pm_positions and meme_positions on 2026-09-26 (v_exposure_lots); venue mechanics: a binary resolves to 0 or 1, and a meme pool can be pulled in one block.",
  ruling="Enact option (b) at R = 10% (migration 41; decided 2026-09-26 by the parent agent under David's delegation). Amended the same day (migration 44): ODDSBORNE binaries and BANDIT memes count at full notional, equities keep to-invalidation. After QUANTANAMO raised its lines it is at 6.4% (was 11.9%, blocked); ODDSBORNE and BANDIT have no open lots (0%).",
  amendment="Open risk <= 10% of book per steward, gap-prone lots (binaries, memes) at full notional and equities to invalidation; guidance sizes down or blocks and reports `risk_basis`.",
  growth_cost="Caps stacking; at a 10% invalidation distance equities still allow ~100% of book in positions. BANDIT holds about 1.5 starters at once (0.180 SOL budget), ODDSBORNE about 10% of book in open tickets.", ruin_reduction="Bounds the loss if every open lot hits its invalidation at once (equities) or goes to zero (binaries, memes) to 10% of book.",
  interactions="cash-only-no-margin, required-invalidation, edge-max-stake, starter-stake.", next_review="2026-10-26"),
dict(
  id="shadow-exits", title="Shadow (paper) exit tracking",
  status="in_force", status_after="in_force", verdict="uphold", needs_david=False,
  purpose="Test alternative exit rules without trading them. Promote a rule only once it beats real exits.",
  mechanism="`meta.paper_<rule>` on lot rows; `v_shadow_exits`, `v_shadow_exit_scorecard` (promotable at n >= 10 and LCB of paper - real > 0).",
  paths=["supabase/schemas/32_shadow_exits.sql", "supabase/schemas/33_shadow_exits_definer.sql"],
  growth="Positive: finds better exits at no cost.", ruin="None.",
  statistics="Same LCB bar as the stake rule; n = 4 today for bank_at_+20pct (LCB -10.5 pts).",
  incentives="Promotion is by evidence.", evidence="Live scorecard.", ruling="Uphold.", amendment="None.",
  growth_cost="None.", ruin_reduction="None.", interactions="None.", next_review="2026-11-26"),
]
