import { describe, expect, test } from 'bun:test';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

const dashboardRoot = join(import.meta.dir, '..');

async function readDashboard(relative: string): Promise<string> {
  return readFile(join(dashboardRoot, relative), 'utf8');
}

describe('desk IA smoke', () => {
  test('chrome lands on Board; Book is /book; Home and Risk are gone as destinations', async () => {
    const app = await readDashboard('app/terminal/app.tsx');
    const book = await readDashboard('app/terminal/book-panel.tsx');
    const nav = await readDashboard('lib/desk-nav.ts');
    expect(app).toContain("surface === 'events'");
    expect(app).toContain("surface === 'theses'");
    expect(app).toContain("surface === 'leaderboard'");
    expect(app).toContain('isSwipeSurface');
    expect(app).toContain('team: <TeamPanel');
    expect(app).toContain('<BookPanel');
    expect(app).toContain('<TeamPanel');
    expect(app).toContain('<LeaderboardPanel');
    expect(app).toContain('assembleDeskFreshness');
    expect(app).toContain('FreshnessChips');
    expect(app).not.toContain('LastRunChip');
    expect(app).not.toContain('shortRoutine');
    expect(app).not.toContain("surface === 'home'");
    expect(app).not.toContain("surface === 'risk'");
    expect(app).not.toContain('RiskPanel');
    expect(app).not.toContain('HomePanel');
    expect(app).not.toContain('RISK CONTROLS');
    expect(app).not.toContain('3 buys');
    expect(app).not.toContain('20%');
    expect(nav).toContain("id: 'book'");
    expect(nav).toContain("id: 'team'");
    expect(nav).toContain("id: 'leaderboard'");
    expect(nav).toContain("href: '/team'");
    expect(nav).toContain("href: '/book'");
    expect(nav).toContain("href: '/', id: 'leaderboard'");
    expect(nav).toContain("go: 'm'");
    expect(nav).toContain("go: 'p'");
    expect(nav).toContain('DESK_SWIPE_SURFACES');
    expect(nav).toContain("'leaderboard', 'book', 'team'");
    expect(nav).toContain('PUBLIC_DESK_TABS');
    expect(nav).not.toMatch(/id: 'home'/);
    expect(nav).not.toMatch(/id: 'risk'/);
    expect(nav).not.toMatch(/label: 'Home'/);
    expect(nav).not.toMatch(/label: 'Risk'/);
    expect(nav).not.toMatch(/Polymarket/);
    expect(app).toContain('VenueFilterBar');
    expect(book).not.toContain('VenueFilterBar');
    expect(book).toContain('assembleBookEdge');
    expect(book).toContain('assembleBookOpen');
  });

  test('product chrome is grasshopper; venue shorts are STOCKS / PREDICTIONS / COINS', async () => {
    const app = await readDashboard('app/terminal/app.tsx');
    const shell = await readDashboard('app/terminal/public-shell.tsx');
    const signIn = await readDashboard('app/auth/sign-in.tsx');
    const layout = await readDashboard('app/layout.tsx');
    const venue = await readDashboard('lib/desk-venue.ts');
    const book = await readDashboard('app/terminal/book-panel.tsx');
    const chips = await readDashboard('app/terminal/venue-filter.tsx');
    const tests = await readDashboard('app/terminal/backtests-panel.tsx');
    expect(app).toMatch(/term-brand[\s\S]{0,180}GRASSHOPPER\s*<\/a>/);
    expect(app).not.toMatch(/term-brand[\s\S]{0,180}QUANTANAMO/);
    expect(app).not.toContain('no QUANTANAMO run');
    expect(app).not.toContain("label: 'scan'");
    expect(app).toContain("chip.label} · {age");
    expect(shell).toContain('GRASSHOPPER');
    expect(shell).toContain('CrtBoot');
    expect(shell).toContain("prefers-reduced-motion: reduce");
    expect(shell).toContain('setBoot');
    expect(signIn).toContain('>GRASSHOPPER<');
    expect(layout).toContain("title: 'Grasshopper'");
    expect(venue).toContain("short: 'STOCKS'");
    expect(venue).toContain("short: 'PREDICTIONS'");
    expect(venue).toContain("short: 'COINS'");
    expect(venue).toContain("label: 'STOCKS'");
    expect(venue).toContain("label: 'PREDICTIONS'");
    expect(venue).toContain("label: 'COINS'");
    expect(venue).toContain("return 'ODDSBORNE'");
    expect(venue).toContain("return 'BANDIT'");
    expect(venue).toContain("return 'PREDICTIONS'");
    expect(venue).toContain("return 'COINS'");
    expect(book).toContain('assembleBookEdge');
    expect(book).toContain('asciiFillBar');
    expect(book).toContain('crt-book');
    expect(book).toContain('StewardAvatar');
    expect(book).toContain('GOOD');
    expect(book).toContain('HOLD');
    expect(book).not.toContain('CoinNote');
    expect(book).not.toContain('assembleDeskBookRollup');
    expect(book).not.toContain("venue === 'all'");
    expect(book).not.toContain('compact={venue === \'all\'}');
    expect(chips).toContain('venueShort(venue)');
    expect(chips).not.toContain("'EQ'");
    expect(chips).not.toContain("'PM'");
    expect(tests).toContain('term-tests-cards');
    expect(tests).toContain('term-test-card');
    expect(tests).toContain('term-test-trades-cards');
    const team = await readDashboard('app/terminal/team-panel.tsx');
    const idCard = await readDashboard('app/terminal/steward-id-card.tsx');
    const pager = await readDashboard('app/terminal/desk-pager.tsx');
    const avatars = await readDashboard('app/terminal/steward-avatar.tsx');
    const living = await readDashboard('app/terminal/steward-living.tsx');
    const avatarLib = await readDashboard('lib/desk-avatar.ts');
    const avatarCss = await readDashboard('app/terminal/steward-avatar.module.css');
    const icon = await readDashboard('lib/steward-icon.ts');
    const motion = await readDashboard('lib/steward-motion.ts');
    const css = await readDashboard('app/globals.css');
    expect(team).toContain('desk_agents');
    expect(team).toContain('stewardIdCards');
    expect(team).toContain('StewardIdCard');
    expect(team).toContain('steward-deck');
    expect(team).toContain('steward-dragger');
    expect(team).toContain('data-card-dragger');
    expect(team).toContain('steward-deck-track');
    expect(team).toContain('live=');
    expect(team).not.toContain('pnl');
    expect(team).not.toContain('win_rate');
    expect(team).not.toContain('heartbeat');
    expect(team).not.toContain('clipCharter');
    expect(team).not.toContain('Liveline');
    expect(idCard).toContain('data-finish="ledger"');
    expect(idCard).toContain('StewardAvatar');
    expect(idCard).toContain('size="card"');
    expect(idCard).toContain('StewardHeroCard');
    expect(idCard).toContain('isWebGL2Available');
    expect(idCard).not.toContain('@rive-app');
    expect(idCard).not.toContain('vgpu');
    expect(idCard).not.toContain('ektogamat');
    expect(idCard).not.toContain('scanline');
    const hero = await readDashboard('app/terminal/steward-hero-card.tsx');
    const foil = await readDashboard('lib/steward-foil.ts');
    const stock = await readDashboard('lib/steward-card-stock.ts');
    const mesh = await readDashboard('lib/steward-card-mesh.ts');
    expect(hero).toContain('from \'three\'');
    expect(hero).toContain('WebGLRenderer');
    expect(hero).toContain('RoomEnvironment');
    expect(hero).toContain('RectAreaLight');
    expect(hero).toContain('cardPixelRatio');
    expect(hero).toContain('IntersectionObserver');
    expect(hero).not.toContain('scanline');
    expect(hero).not.toContain('HolographicMaterial');
    expect(foil).toContain('MeshPhysicalMaterial');
    expect(foil).toContain('onBeforeCompile');
    expect(foil).toContain('clearcoat');
    expect(foil).toContain('iridescence');
    expect(foil).toContain('uFoilMap');
    expect(foil).not.toContain('scanline');
    expect(foil).not.toContain('hologram');
    expect(stock).toContain('STEWARD_CARD_DPR_CAP');
    expect(mesh).toContain('RoundedBoxGeometry');
    expect(mesh).toContain('card-core');
    expect(mesh).toContain('card-print-front');
    expect(mesh).toContain('StewardFoilMaterial');
    expect(pager).toContain('pagerScrollToBehavior');
    expect(pager).toContain('wrapSwipeSurface');
    expect(pager).toContain('wrapFromEdgeDrag');
    expect(pager).toContain('DESK_PAGER_SLOTS');
    expect(pager).toContain('data-clone');
    expect(pager).toContain('canonicalPane');
    expect(pager).toContain('if (gesture.armed) return');
    expect(pager).toContain('isSwipeWrap');
    expect(pager).toContain('pageSwipeConsumesTarget');
    expect(pager).toContain('data-circular');
    expect(pager).toContain('data-desk-pane-scroll');
    expect(pager).toContain('scrollTo');
    expect(app).toContain('PUBLIC_DESK_TABS');
    expect(app).toContain('<DeskPager');
    expect(app).toContain("surface === 'theses'");
    expect(app).toContain('<ThesesWorld');
    expect(app).toContain("from './theses-world'");
    expect(app).not.toContain('theses: publicView');
    expect(app).toContain('prefers-reduced-motion: reduce');
    const world = await readDashboard('app/terminal/theses-world.tsx');
    const districts = await readDashboard('lib/thesis-districts.ts');
    expect(world).toContain('assembleThesisDistricts');
    expect(world).toContain('thesis-districts');
    expect(world).toContain('thesis-page');
    expect(world).toContain('Back to the district');
    expect(world).toContain('NOT_IN_LEDGER');
    expect(world).toContain('pagerScrollBehavior');
    expect(world).toContain('ThesisIslandView');
    expect(world).toContain('ThesisIslandPoster');
    expect(world).not.toContain("from 'three'");
    expect(world).not.toContain('WebGLRenderer');
    expect(world).not.toContain('Liveline');
    expect(world).not.toContain('win_rate');
    expect(world).not.toContain('assembleBookEdge');
    expect(world).not.toContain('StewardIdCard');
    expect(districts).toContain("kind === 'theme'");
    expect(districts).toContain('isLiveThesis');
    expect(districts).not.toContain('win_rate');
    expect(css).toContain('.thesis-world');
    expect(css).toContain('.thesis-districts');
    expect(css).toContain('.thesis-island');
    expect(css).toContain('#f3ead8');
    expect(css).toContain('.term.is-theses');
    expect(css).toContain('100dvh');
    expect(css).not.toContain('.thesis-bldg');
    expect(css).not.toContain('thesis-idle');
    const islandView = await readDashboard('app/terminal/thesis-island-view.tsx');
    const islandLib = await readDashboard('lib/thesis-island.ts');
    expect(islandView).toContain('WebGLRenderer');
    expect(islandView).toContain('BokehPass');
    expect(islandView).toContain('islandPixelRatio');
    expect(islandView).toContain('failIfMajorPerformanceCaveat');
    expect(islandView).toContain('isWebGL2Available');
    expect(islandView).toContain('reduceMotion');
    expect(islandView).toContain('island.group.rotation.y = 0');
    expect(islandView).not.toContain('GLTFLoader');
    expect(islandView).not.toContain('hologram');
    expect(islandLib).toContain('LatheGeometry');
    expect(islandLib).toContain('IcosahedronGeometry');
    expect(islandLib).toContain('paintThesisSign');
    expect(islandLib).toContain('ExtrudeGeometry');
    expect(islandLib).not.toContain('ConeGeometry');
    expect(islandLib).not.toContain('GLTFLoader');
    expect(islandLib).not.toContain('emoji');
    expect(avatars).toContain('StewardLivingIcon');
    expect(avatars).toContain('aria-label={label}');
    expect(avatars).toContain('role="img"');
    expect(avatars).toContain('data-runtime="icon"');
    expect(avatars).not.toContain('StewardRiveFace');
    expect(avatars).not.toContain('StewardBot');
    expect(avatars).not.toContain('@rive-app');
    expect(avatars).not.toContain('TabletMark');
    expect(avatars).not.toContain('BlobMark');
    expect(avatars).not.toContain('GrasshopperMark');
    expect(avatars).not.toContain('lorelei');
    expect(avatars).not.toContain('@dicebear');
    expect(avatarLib).not.toContain('@dicebear');
    expect(avatarLib).toContain('StewardBotKind');
    expect(avatarLib).toContain("case 'quantanamo'");
    expect(avatarLib).toContain('living icons');
    expect(avatarLib).toContain('stewardMood');
    expect(avatarLib).toContain('stewardSpecies');
    expect(avatarLib).not.toContain('stewardSilhouette');
    expect(avatarLib).not.toContain('stewardMeshSpec');
    expect(avatarLib).not.toContain("from 'three'");
    expect(living).toContain('requestAnimationFrame');
    expect(living).toContain('composeStewardPose');
    expect(living).toContain('data-icon="circle-eyes"');
    expect(living).not.toContain('@rive-app');
    expect(living).not.toContain('.riv');
    expect(living).not.toContain('from \'three\'');
    expect(living).not.toContain('WebGLRenderer');
    expect(icon).toContain('composeStewardPose');
    expect(icon).toContain('paintStewardIcon');
    expect(icon).toContain('sphereWrap');
    expect(icon).toContain('arc');
    expect(icon).toContain('roundRect');
    expect(icon).not.toContain('shadowBlur');
    expect(icon).not.toContain('feTurbulence');
    expect(icon).not.toContain('BotMouth');
    expect(icon).not.toContain('Minion');
    expect(motion).toContain('stewardBlinkCover');
    expect(motion).toContain('stewardBreathe');
    expect(motion).toContain('stewardGlanceX');
    expect(motion).toContain('stewardPulse');
    expect(motion).toContain('stewardThinkAmount');
    expect(motion).toContain('pinchThenForm');
    expect(motion).toContain('stewardBangAmount');
    expect(motion).toContain('approachParam');
    expect(team).toContain('cards.map');
    expect(team).toContain('StewardCardDragger');
    expect(team).not.toContain('IntersectionObserver');
    expect(team).not.toContain('scroll-snap');
    expect(avatars).toContain('size === \'card\'');
    expect(avatars).not.toContain('from \'three\'');
    expect(avatars).toContain('mood=');
    expect(css).toContain('prefers-reduced-motion');
    expect(css).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))');
    expect(css).toContain('.line-frame > div:has(canvas)');
    expect(css).toContain('.desk-pager');
    expect(css).toContain('.term.is-swipe');
    expect(css).toContain('minmax(0');
    expect(css).toContain('.steward-dragger');
    expect(css).toContain('.steward-deck-track');
    expect(css).toContain('.is-theses');
    expect(css).toContain('.steward-deck');
    expect(css).toContain('.id-card');
    expect(css).toContain('.id-card-webgl');
    expect(css).toContain('.steward-deck');
    expect(css).toContain('overflow: visible');
    expect(css).not.toMatch(/\.term-public \.term-brand \{[^}]*letter-spacing: 0\.16em/);
    expect(avatarCss).toContain('prefers-reduced-motion');
    expect(avatarCss).toContain('overflow: visible');
    expect(avatarCss).toContain('.steward');
    expect(avatarCss).toContain('.icon');
    expect(avatarCss).not.toContain('steward-bounce');
    expect(avatarCss).not.toContain('steward-blink');
    expect(avatarCss).not.toContain('steward-glance');
    expect(avatarCss).not.toContain('.stage');
    expect(avatarCss).not.toContain('.riv');
    expect(avatarCss).not.toContain('feTurbulence');
    expect(avatarCss).not.toContain('.strap');
    expect(avatarCss).not.toContain('.lidRest');
    expect(avatarCss).not.toContain('.rivet');
    expect(avatarCss).not.toContain('.treadTooth');
    expect(avatarCss).not.toContain('.vent');
    expect(avatarCss).not.toContain('steward-nod');
    expect(avatarCss).not.toContain('steward-beep');
    expect(css).toContain('--font-brand');
    expect(css).toContain('Special Elite');
    expect(css).toContain('.crt-boot');
    expect(css).toContain('.crt-tape');
    expect(css).toContain('.crt-scan');
    expect(layout).toContain('Special+Elite');
  });

  test('Board stays Liveline-first; Book is CRT edge, not a Rive tape', async () => {
    const book = await readDashboard('app/terminal/book-panel.tsx');
    const app = await readDashboard('app/terminal/app.tsx');
    const board = await readDashboard('app/terminal/leaderboard-panel.tsx');
    const wrap = await readDashboard('app/terminal/desk-liveline.tsx');
    const openStrip = await readDashboard('app/terminal/book-open-strip.tsx');
    const openMap = await readDashboard('lib/book-open-strip.ts');
    const map = await readDashboard('lib/desk-liveline.ts');
    const css = await readDashboard('app/globals.css');
    expect(book).toContain('assembleBookEdge');
    expect(book).toContain('assembleBookOpen');
    expect(book).toContain('<BookOpenStrip');
    expect(book).toContain('crt-book-readout');
    expect(book).not.toContain('<DeskLiveline');
    expect(book).not.toContain('<BookTable');
    expect(book).not.toContain('BookExploded');
    expect(book).not.toContain('cluster.rotation');
    expect(book).not.toContain('@rive-app');
    expect(book).not.toContain('skills.riv');
    expect(app).not.toContain('BookExploded');
    expect(app).not.toContain('from \'three\'');
    expect(app).toContain("from './team-panel'");
    expect(app).toContain("from './leaderboard-panel'");
    expect(board).toContain('assembleLeaderboard');
    expect(board).toContain('assembleLiveline');
    expect(board).toContain('StewardAvatar');
    expect(board).toContain('size="board"');
    expect(board).toContain('stewardMood');
    expect(board).toContain('DeskLiveline');
    expect(board).toContain('CrtTape');
    expect(board).not.toContain('line-foci');
    expect(board).not.toContain("label: 'ALL'");
    expect(board).not.toContain('setFocus');
    expect(board).not.toContain('TeamAvatar');
    expect(board).toContain('NOT_RANKED');
    expect(board).not.toContain('0.00%');
    expect(board).not.toContain('@rive-app');
    expect(board).not.toContain('the line');
    expect(board).not.toContain('line-mast');
    expect(board).not.toContain('<h1>Board</h1>');
    expect(board).toContain('visually-hidden');
    expect(board).not.toContain('TradeReplay');
    expect(board).not.toContain('threeui');
    expect(board).not.toContain('ascii-magic');
    expect(book).toContain('visually-hidden');
    expect(book).toContain('BOOK // EDGE');
    expect(css).toContain('.crt-book');
    expect(css).toContain('.book-open');
    expect(css).toContain('.crt-book .book-open-line.line-frame > div:has(canvas)');
    expect(css).toContain('crt-book-sweep');
    expect(css).toContain('.term-fresh');
    expect(wrap).toContain("from 'liveline'");
    expect(wrap).toContain('theme="dark"');
    expect(wrap).toContain('referenceLine');
    expect(wrap).toContain('compact');
    expect(wrap).toContain("compact ? () => ''");
    expect(openStrip).toContain('referenceLine');
    expect(openStrip).toContain('compact');
    expect(openStrip).not.toContain('StewardAvatar');
    expect(openStrip).not.toContain('book-open-lede');
    expect(openStrip).not.toContain('book-open-who');
    expect(openStrip).not.toContain('venue_label');
    expect(openStrip).not.toContain('PREDICTIONS');
    expect(openStrip).not.toContain('cost ${');
    expect(openMap).toContain('pm_positions.mark');
    expect(openMap).toContain('pm_markets.last_yes');
    expect(openMap).toContain('pm_fills.price');
    expect(openMap).toContain('average_cost');
    expect(openMap).toContain('kill_mid');
    expect(openMap).not.toContain('clobTokenIds');
    expect(map).toContain('unix seconds');
    expect(map).toContain('never SOL→USD');
  });
});
