-- ThesisForge canonical Postgres schema.
-- Browser roles have no table privileges; trusted jobs and server routes use
-- the postgres connection or a Supabase secret key stored outside the repo.

create table public.runs (
  id bigint generated by default as identity primary key,
  run_type text not null,
  started_at timestamptz not null,
  completed_at timestamptz,
  notes text
);

-- Mirror of Codex's local automation registry. The automation id is stable
-- across schedule edits and is the natural key used by Codex run records.
create table public.codex_automations (
  id text primary key,
  name text not null,
  prompt text not null,
  kind text not null default 'cron',
  status text not null check (status in ('ACTIVE', 'PAUSED')),
  rrule text not null,
  model text,
  reasoning_effort text,
  execution_environment text,
  project_id text,
  working_directories jsonb not null default '[]'::jsonb,
  next_run_at timestamptz,
  last_run_at timestamptz,
  source_created_at timestamptz not null,
  source_updated_at timestamptz not null,
  indexed_at timestamptz not null default now()
);
create index idx_codex_automations_status_next_run
  on public.codex_automations(status, next_run_at);

-- One immutable row per Codex automation thread/run. Rich JSON columns retain
-- variable investigation output while the high-value operational fields stay
-- typed and indexed for dashboard filters.
create table public.codex_automation_runs (
  thread_id text primary key,
  automation_id text not null references public.codex_automations(id) on delete cascade,
  status text not null,
  outcome text not null check (outcome in ('running', 'passed', 'failed', 'cancelled', 'unknown')),
  started_at timestamptz not null,
  completed_at timestamptz,
  duration_ms bigint check (duration_ms is null or duration_ms >= 0),
  title text,
  summary text,
  final_output text,
  findings jsonb not null default '[]'::jsonb,
  learnings jsonb not null default '[]'::jsonb,
  explored jsonb not null default '[]'::jsonb,
  actions jsonb not null default '[]'::jsonb,
  timeline jsonb not null default '[]'::jsonb,
  error_text text,
  tokens_used bigint check (tokens_used is null or tokens_used >= 0),
  source_metadata jsonb not null default '{}'::jsonb,
  indexed_at timestamptz not null default now()
);
create index idx_codex_automation_runs_automation_started
  on public.codex_automation_runs(automation_id, started_at desc);
create index idx_codex_automation_runs_outcome_started
  on public.codex_automation_runs(outcome, started_at desc);

create table public.bookmarks (
  id text primary key,
  author_id text,
  created_at timestamptz,
  fetched_at timestamptz not null,
  text text not null,
  raw_json jsonb not null,
  market_score smallint not null default 0 check (market_score between 0 and 100),
  is_market_related boolean not null default false
);

create table public.bookmark_urls (
  bookmark_id text not null references public.bookmarks(id) on delete cascade,
  url text not null,
  expanded_url text,
  display_url text,
  primary key (bookmark_id, url)
);

create table public.symbols (
  symbol text primary key,
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  mention_count bigint not null default 0 check (mention_count >= 0),
  source_count bigint not null default 0 check (source_count >= 0),
  status text not null default 'candidate'
);

create table public.bookmark_symbols (
  bookmark_id text not null references public.bookmarks(id) on delete cascade,
  symbol text not null references public.symbols(symbol) on delete cascade,
  source text not null,
  primary key (bookmark_id, symbol)
);
create index idx_bookmark_symbols_symbol on public.bookmark_symbols(symbol);

create table public.claims (
  id bigint generated by default as identity primary key,
  bookmark_id text not null references public.bookmarks(id) on delete cascade,
  claim_text text not null,
  claim_type text not null,
  created_at timestamptz not null,
  confidence smallint not null default 40 check (confidence between 0 and 100)
);
create index idx_claims_bookmark_id on public.claims(bookmark_id);

create table public.theses (
  id text primary key,
  name text not null,
  summary text not null,
  status text not null default 'forming',
  confidence smallint not null default 40 check (confidence between 0 and 100),
  time_horizon text not null default 'days_to_weeks',
  created_at timestamptz not null,
  updated_at timestamptz not null,
  stance text not null default 'neutral' check (stance in ('bullish', 'bearish', 'neutral')),
  variant_perception text,
  falsifier text
);

-- Database-backed ontology catalog. Code supplies scoring and promotion
-- mechanics; the evolving taxonomy and its evidence live in Supabase.
create table public.ontology_themes (
  id text primary key,
  thesis_id text unique references public.theses(id) on delete set null,
  kind text not null default 'theme' check (kind in ('theme', 'concept')),
  name text not null,
  description text not null default '',
  status text not null default 'candidate' check (status in ('candidate', 'active', 'merged', 'retired')),
  parent_theme_id text references public.ontology_themes(id) on delete set null,
  merged_into_theme_id text references public.ontology_themes(id) on delete set null,
  match_threshold smallint not null default 35 check (match_threshold between 0 and 100),
  auto_promote_sources smallint not null default 3 check (auto_promote_sources >= 2),
  created_by text not null default 'learning',
  created_at timestamptz not null,
  updated_at timestamptz not null,
  check (id <> parent_theme_id),
  check (id <> merged_into_theme_id)
);
create index idx_ontology_themes_status_kind on public.ontology_themes(status, kind);
create index idx_ontology_themes_parent on public.ontology_themes(parent_theme_id) where parent_theme_id is not null;
create index idx_ontology_themes_merged_into on public.ontology_themes(merged_into_theme_id) where merged_into_theme_id is not null;

create table public.ontology_terms (
  id bigint generated always as identity primary key,
  theme_id text not null references public.ontology_themes(id) on delete cascade,
  term text not null,
  normalized_term text not null,
  term_type text not null default 'keyword' check (term_type in ('keyword', 'alias', 'phrase', 'entity', 'negative')),
  weight smallint not null default 50 check (weight between 1 and 100),
  status text not null default 'candidate' check (status in ('candidate', 'active', 'rejected')),
  evidence_count bigint not null default 0 check (evidence_count >= 0),
  source_count bigint not null default 0 check (source_count >= 0),
  created_by text not null default 'learning',
  created_at timestamptz not null,
  updated_at timestamptz not null,
  unique (theme_id, normalized_term)
);
create index idx_ontology_terms_normalized_active on public.ontology_terms(normalized_term) where status = 'active';
create index idx_ontology_terms_theme_status on public.ontology_terms(theme_id, status);

create table public.ontology_lexicon (
  token text not null,
  token_type text not null check (token_type in ('ignored_symbol', 'market_keyword', 'market_context', 'candidate_stopword')),
  weight smallint not null default 0 check (weight between 0 and 100),
  status text not null default 'active' check (status in ('active', 'retired')),
  reason text,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  primary key (token, token_type)
);
create index idx_ontology_lexicon_type_status on public.ontology_lexicon(token_type, status);

create table public.symbol_theme_memberships (
  symbol text not null references public.symbols(symbol) on delete cascade,
  theme_id text not null references public.ontology_themes(id) on delete cascade,
  relationship text not null default 'member' check (relationship in ('member', 'beneficiary', 'supplier', 'customer', 'competitor', 'proxy')),
  confidence smallint not null default 40 check (confidence between 0 and 100),
  evidence_count bigint not null default 0 check (evidence_count >= 0),
  source_count bigint not null default 0 check (source_count >= 0),
  status text not null default 'candidate' check (status in ('candidate', 'active', 'rejected')),
  learned_by text not null default 'cooccurrence',
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  primary key (symbol, theme_id)
);
create index idx_symbol_theme_memberships_theme_status on public.symbol_theme_memberships(theme_id, status, confidence desc);

create table public.ontology_observations (
  source_type text not null,
  source_key text not null,
  feature_type text not null check (feature_type in ('term', 'symbol', 'hashtag')),
  feature_value text not null,
  occurrences smallint not null default 1 check (occurrences > 0),
  observed_at timestamptz not null,
  primary key (source_type, source_key, feature_type, feature_value)
);
create index idx_ontology_observations_feature on public.ontology_observations(feature_type, feature_value, observed_at desc);

create table public.ontology_evidence (
  id bigint generated always as identity primary key,
  source_type text not null,
  source_key text not null,
  theme_id text not null references public.ontology_themes(id) on delete cascade,
  feature_type text not null,
  feature_value text not null,
  match_method text not null check (match_method in ('term', 'symbol', 'cooccurrence', 'manual', 'historical')),
  score smallint not null check (score between 0 and 100),
  observed_at timestamptz not null,
  unique (source_type, source_key, theme_id, feature_type, feature_value, match_method)
);
create index idx_ontology_evidence_theme_date on public.ontology_evidence(theme_id, observed_at desc);
create index idx_ontology_evidence_source on public.ontology_evidence(source_type, source_key);

create table public.ontology_candidates (
  id bigint generated always as identity primary key,
  candidate_type text not null check (candidate_type in ('theme', 'term', 'membership')),
  candidate_key text not null,
  proposed_theme_id text references public.ontology_themes(id) on delete cascade,
  proposed_label text not null,
  proposed_description text not null default '',
  score smallint not null default 0 check (score between 0 and 100),
  evidence_count bigint not null default 0 check (evidence_count >= 0),
  source_count bigint not null default 0 check (source_count >= 0),
  status text not null default 'pending' check (status in ('pending', 'promoted', 'rejected')),
  sample_context jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  reviewed_at timestamptz,
  review_note text,
  unique (candidate_type, candidate_key)
);
create index idx_ontology_candidates_status_score on public.ontology_candidates(status, score desc, source_count desc);
create index idx_ontology_candidates_theme_status on public.ontology_candidates(proposed_theme_id, status) where proposed_theme_id is not null;

create table public.ontology_candidate_evidence (
  candidate_id bigint not null references public.ontology_candidates(id) on delete cascade,
  source_type text not null,
  source_key text not null,
  evidence_score smallint not null check (evidence_score between 0 and 100),
  context jsonb not null default '{}'::jsonb,
  observed_at timestamptz not null,
  primary key (candidate_id, source_type, source_key)
);
create index idx_ontology_candidate_evidence_source on public.ontology_candidate_evidence(source_type, source_key);

create table public.thesis_symbols (
  thesis_id text not null references public.theses(id) on delete cascade,
  symbol text not null references public.symbols(symbol) on delete cascade,
  role text not null default 'candidate',
  weight_hint double precision not null default 0,
  primary key (thesis_id, symbol)
);
create index idx_thesis_symbols_symbol on public.thesis_symbols(symbol);

create table public.thesis_evidence (
  id bigint generated by default as identity primary key,
  thesis_id text not null references public.theses(id) on delete cascade,
  bookmark_id text references public.bookmarks(id) on delete set null,
  evidence_type text not null,
  direction text not null,
  summary text not null,
  source_url text,
  confidence smallint not null default 40 check (confidence between 0 and 100),
  created_at timestamptz not null
);
create index idx_thesis_evidence_thesis_id on public.thesis_evidence(thesis_id);
create index idx_thesis_evidence_bookmark_id on public.thesis_evidence(bookmark_id);

create table public.thesis_scores (
  id bigint generated by default as identity primary key,
  thesis_id text not null references public.theses(id) on delete cascade,
  scored_at timestamptz not null,
  confidence smallint not null check (confidence between 0 and 100),
  momentum smallint not null check (momentum between 0 and 100),
  evidence_quality smallint not null check (evidence_quality between 0 and 100),
  catalyst_strength smallint not null check (catalyst_strength between 0 and 100),
  portfolio_fit smallint not null check (portfolio_fit between 0 and 100),
  risk smallint not null check (risk between 0 and 100),
  notes text
);
create index idx_thesis_scores_thesis_id on public.thesis_scores(thesis_id);

create table public.catalysts (
  id bigint generated by default as identity primary key,
  thesis_id text references public.theses(id) on delete set null,
  symbol text references public.symbols(symbol) on delete set null,
  catalyst_type text not null,
  event_date date,
  summary text not null,
  source text not null,
  status text not null default 'watching',
  created_at timestamptz not null
);
create index idx_catalysts_thesis_id on public.catalysts(thesis_id);
create index idx_catalysts_symbol on public.catalysts(symbol);

create table public.portfolio_exposure (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null,
  account_last4 text not null,
  symbol text not null,
  quantity numeric(28, 10) not null,
  average_buy_price numeric(20, 6),
  source text not null default 'robinhood_mcp'
);
create index idx_portfolio_exposure_symbol_observed on public.portfolio_exposure(symbol, observed_at desc);

create table public.account_snapshots (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null,
  account_label text not null,
  total_value numeric(20, 4) not null,
  equity_value numeric(20, 4) not null,
  cash numeric(20, 4) not null,
  buying_power numeric(20, 4) not null,
  source text not null default 'robinhood_mcp'
);
create index idx_account_snapshots_observed_at on public.account_snapshots(observed_at desc);

create table public.trade_proposals (
  id bigint generated by default as identity primary key,
  thesis_id text references public.theses(id) on delete set null,
  symbol text not null references public.symbols(symbol),
  side text not null check (side in ('buy', 'sell')),
  notional numeric(20, 4) not null check (notional >= 0),
  order_type text not null default 'market_review_only',
  status text not null default 'proposed',
  rationale text not null,
  created_at timestamptz not null,
  reviewed_at timestamptz,
  broker_alerts jsonb
);
create index idx_trade_proposals_thesis_id on public.trade_proposals(thesis_id);
create index idx_trade_proposals_symbol_status on public.trade_proposals(symbol, status);

create table public.postmortems (
  id bigint generated by default as identity primary key,
  trade_proposal_id bigint references public.trade_proposals(id) on delete set null,
  thesis_id text references public.theses(id) on delete set null,
  created_at timestamptz not null,
  outcome text not null,
  lesson text not null
);
create index idx_postmortems_trade_proposal_id on public.postmortems(trade_proposal_id);
create index idx_postmortems_thesis_id on public.postmortems(thesis_id);

create table public.articles (
  id bigint generated by default as identity primary key,
  bookmark_id text not null references public.bookmarks(id) on delete cascade,
  url text not null unique,
  title text,
  fetched_at timestamptz not null,
  status_code integer,
  content_type text,
  text text,
  error text
);
create index idx_articles_bookmark_id on public.articles(bookmark_id);

create table public.graph_nodes (
  id text primary key,
  node_type text not null,
  label text not null,
  properties_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table public.graph_edges (
  id bigint generated by default as identity primary key,
  src_id text not null references public.graph_nodes(id) on delete cascade,
  dst_id text not null references public.graph_nodes(id) on delete cascade,
  edge_type text not null,
  weight double precision not null default 1.0,
  evidence_count bigint not null default 1 check (evidence_count >= 0),
  properties_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  unique (src_id, dst_id, edge_type)
);
create index idx_graph_edges_src_id on public.graph_edges(src_id);
create index idx_graph_edges_dst_id on public.graph_edges(dst_id);

create table public.research_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  label text not null,
  event_date text,
  status text not null default 'watching',
  source_url text,
  summary text not null,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table public.research_queue (
  id bigint generated by default as identity primary key,
  priority smallint not null default 50 check (priority between 0 and 100),
  status text not null default 'open',
  topic text not null,
  reason text not null,
  source text not null,
  created_at timestamptz not null,
  updated_at timestamptz not null
);
create index idx_research_queue_status_priority on public.research_queue(status, priority desc);

create table public.predictions (
  id bigint generated by default as identity primary key,
  external_key text not null unique,
  thesis_id text not null references public.theses(id) on delete cascade,
  statement text not null,
  target_date date,
  probability smallint not null default 50 check (probability between 0 and 100),
  status text not null default 'open',
  resolution_notes text,
  created_at timestamptz not null,
  updated_at timestamptz not null
);
create index idx_predictions_thesis_status on public.predictions(thesis_id, status);

create table public.insights (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  summary text not null,
  insight_type text not null default 'derived',
  novelty smallint not null default 50 check (novelty between 0 and 100),
  confidence smallint not null default 50 check (confidence between 0 and 100),
  status text not null default 'active',
  created_at timestamptz not null,
  updated_at timestamptz not null
);
create index idx_insights_status on public.insights(status);

create table public.insight_links (
  insight_id bigint not null references public.insights(id) on delete cascade,
  node_id text not null references public.graph_nodes(id) on delete cascade,
  relationship text not null default 'connects',
  primary key (insight_id, node_id, relationship)
);
create index idx_insight_links_node_id on public.insight_links(node_id);

create table public.thesis_relations (
  src_thesis_id text not null references public.theses(id) on delete cascade,
  dst_thesis_id text not null references public.theses(id) on delete cascade,
  relation_type text not null,
  strength double precision not null default 1.0,
  rationale text not null,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  primary key (src_thesis_id, dst_thesis_id, relation_type)
);
create index idx_thesis_relations_dst_thesis_id on public.thesis_relations(dst_thesis_id);

create table public.event_decisions (
  event_id bigint primary key references public.research_events(id) on delete cascade,
  decision text not null default 'watch' check (decision in ('participate', 'watch', 'skip')),
  rationale text not null,
  participation_trigger text,
  decided_at timestamptz not null,
  updated_at timestamptz not null
);
create index idx_event_decisions_decision on public.event_decisions(decision);

create table public.research_cycles (
  id bigint generated by default as identity primary key,
  external_key text not null unique,
  thesis_id text not null references public.theses(id) on delete cascade,
  hypothesis text not null,
  preregistered_outcome text not null,
  preregistered_at timestamptz not null,
  stage text not null default 'research',
  status text not null default 'open',
  iteration integer not null default 1 check (iteration > 0),
  market_regime text,
  created_at timestamptz not null,
  updated_at timestamptz not null
);
create index idx_research_cycles_stage on public.research_cycles(stage, status);
create index idx_research_cycles_thesis_id on public.research_cycles(thesis_id);

create table public.strategy_tests (
  id bigint generated by default as identity primary key,
  external_key text not null unique,
  cycle_id bigint not null references public.research_cycles(id) on delete cascade,
  variant_label text not null,
  status text not null default 'queued',
  total_return double precision,
  max_drawdown double precision,
  deflated_sharpe double precision,
  cost_multiplier double precision not null default 1.0 check (cost_multiplier >= 0),
  stress_regime text,
  failure_reason text,
  autopsy text,
  tested_at timestamptz not null
);
create index idx_strategy_tests_cycle_status on public.strategy_tests(cycle_id, status);

create table public.test_scenarios (
  id bigint generated by default as identity primary key,
  test_id bigint not null references public.strategy_tests(id) on delete cascade,
  scenario_key text not null,
  market_regime text not null,
  cost_multiplier double precision not null check (cost_multiplier >= 0),
  outcome text not null,
  metric_value double precision,
  breach_type text,
  tested_at timestamptz not null,
  unique (test_id, scenario_key)
);
create index idx_test_scenarios_test_outcome on public.test_scenarios(test_id, outcome);

create table public.agent_runs (
  id bigint generated by default as identity primary key,
  cycle_id bigint not null references public.research_cycles(id) on delete cascade,
  agent_role text not null,
  independence_group text,
  price_blinded boolean not null default false,
  status text not null default 'complete',
  summary text not null,
  created_at timestamptz not null
);
create index idx_agent_runs_cycle_id on public.agent_runs(cycle_id);

create table public.research_lessons (
  id bigint generated by default as identity primary key,
  cycle_id bigint not null references public.research_cycles(id) on delete cascade,
  test_id bigint references public.strategy_tests(id) on delete set null,
  thesis_id text not null references public.theses(id) on delete cascade,
  lesson_type text not null,
  summary text not null,
  market_regime text,
  incorporated boolean not null default false,
  created_at timestamptz not null
);
create index idx_research_lessons_cycle_id on public.research_lessons(cycle_id);
create index idx_research_lessons_test_id on public.research_lessons(test_id);
create index idx_research_lessons_thesis on public.research_lessons(thesis_id, incorporated);

create table public.risk_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  scope text not null,
  control_type text not null,
  threshold_json jsonb not null,
  enforcement_level text not null default 'code',
  status text not null default 'active',
  updated_at timestamptz not null
);

create table public.financial_api_requests (
  id bigint generated by default as identity primary key,
  provider text not null,
  request_fingerprint text not null,
  method text not null,
  endpoint text not null,
  params_json jsonb not null default '{}'::jsonb,
  body_json jsonb,
  requested_at timestamptz not null,
  completed_at timestamptz not null,
  status_code integer not null,
  response_headers_json jsonb not null default '{}'::jsonb,
  response_sha256 text not null,
  response_encoding text not null default 'gzip',
  response_body bytea not null,
  error_text text
);
create index idx_financial_requests_fingerprint on public.financial_api_requests(request_fingerprint, completed_at desc);

create table public.financial_request_cache (
  request_fingerprint text primary key,
  request_id bigint not null references public.financial_api_requests(id) on delete cascade,
  cached_at timestamptz not null,
  expires_at timestamptz not null,
  freshness_policy text not null
);
create index idx_financial_request_cache_request_id on public.financial_request_cache(request_id);

create table public.financial_access_log (
  id bigint generated by default as identity primary key,
  request_fingerprint text not null,
  request_id bigint references public.financial_api_requests(id) on delete set null,
  access_type text not null check (access_type in ('network', 'cache', 'dry_run', 'blocked')),
  accessed_at timestamptz not null,
  detail text
);
create index idx_financial_access_type_date on public.financial_access_log(access_type, accessed_at desc);
create index idx_financial_access_log_request_id on public.financial_access_log(request_id);

create table public.financial_records (
  id bigint generated by default as identity primary key,
  provider text not null,
  dataset text not null,
  ticker text,
  record_key text not null,
  period text,
  report_period date,
  filing_date date,
  fetched_at timestamptz not null,
  record_sha256 text not null,
  payload_json jsonb not null,
  source_request_id bigint not null references public.financial_api_requests(id) on delete cascade,
  unique (provider, dataset, record_key, record_sha256)
);
create index idx_financial_records_ticker_dataset on public.financial_records(ticker, dataset, report_period desc);
create index idx_financial_records_source_request on public.financial_records(source_request_id);

create table public.dashboard_snapshots (
  id text primary key,
  generated_at timestamptz not null,
  payload jsonb not null
);

-- Supabase exposes public by default. Keep every table deny-by-default for
-- browser roles; trusted server jobs use service_role or a Postgres connection.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'runs','codex_automations','codex_automation_runs','bookmarks','bookmark_urls','symbols','bookmark_symbols','claims','theses',
    'ontology_themes','ontology_terms','ontology_lexicon','symbol_theme_memberships',
    'ontology_observations','ontology_evidence','ontology_candidates','ontology_candidate_evidence',
    'thesis_symbols','thesis_evidence','thesis_scores','catalysts','portfolio_exposure',
    'account_snapshots','trade_proposals','postmortems','articles','graph_nodes','graph_edges',
    'research_events','research_queue','predictions','insights','insight_links','thesis_relations',
    'event_decisions','research_cycles','strategy_tests','test_scenarios','agent_runs',
    'research_lessons','risk_controls','financial_api_requests','financial_request_cache',
    'financial_access_log','financial_records','dashboard_snapshots'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
    execute format('grant all on table public.%I to service_role', table_name);
  end loop;
end $$;

grant usage on schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
alter default privileges in schema public revoke all on tables from anon, authenticated;
alter default privileges in schema public grant all on tables to service_role;
alter default privileges in schema public grant usage, select on sequences to service_role;
