/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 73203f7497c96d6af78e75c40d091777)
interface __BaseEnv_Env {
	DESK_SNAPSHOT: KVNamespace;
	ASSETS: Fetcher;
	DESK_SUPABASE_URL: "https://xqungxapqicdmboniezz.supabase.co";
	DESK_PUBLISH_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DESK_SUPABASE_URL" | "DESK_PUBLISH_TOKEN">> {}
}
