/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false`
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	DESK_SUPABASE_URL: "https://xqungxapqicdmboniezz.supabase.co";
	DESK_READER_APIKEY: string;
	DESK_READER_JWT: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DESK_SUPABASE_URL" | "DESK_READER_APIKEY" | "DESK_READER_JWT">> {}
}
