/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: e9d140cc220790696665b03c5878e7ed)
interface __BaseEnv_Env {
	INTERNAL_SERVICE_TOKEN_SECRET?: SecretsStoreSecret;
	INTERNAL_SERVICE_TOKEN?: string;
	SUPABASE_URL: string;
	SUPABASE_PUBLISHABLE_KEY: string;
	THESISFORGE_DASHBOARD_TOKEN: string;
	THESISFORGE_MANAGER_TOKEN: string;
	THESISFORGE_MANAGER_USER_IDS: string;
	LOCAL_DEV_IDENTITY?: string;
	CF_ACCESS_TEAM_DOMAIN: string;
	CF_ACCESS_AUD: string;
	KNOWLEDGE_PIPELINE: Fetcher /* thesisforge-knowledge-pipeline */;
	RESEARCH_ORCHESTRATOR: Fetcher /* thesisforge-research-orchestrator */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY" | "THESISFORGE_DASHBOARD_TOKEN" | "THESISFORGE_MANAGER_TOKEN" | "THESISFORGE_MANAGER_USER_IDS" | "CF_ACCESS_TEAM_DOMAIN" | "CF_ACCESS_AUD">> {}
}
