create table public.research_documents (
  id bigint generated by default as identity primary key,
  sha256 text not null unique check (sha256 ~ '^[0-9a-f]{64}$'),
  storage_bucket text not null default 'research-originals',
  storage_path text not null unique,
  mime_type text not null,
  document_type text not null check (
    document_type in ('article','filing','pdf','transcript','presentation','spreadsheet','image','other')
  ),
  byte_size bigint not null check (byte_size >= 0),
  extracted_text text,
  extraction_status text not null check (
    extraction_status in ('complete','pending','unsupported','failed')
  ),
  extraction_error text,
  captured_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index idx_research_documents_type_captured
  on public.research_documents(document_type, captured_at desc);
create index idx_research_documents_extraction_status
  on public.research_documents(extraction_status, captured_at desc)
  where extraction_status <> 'complete';
create index idx_research_documents_text_search
  on public.research_documents using gin (to_tsvector('english', coalesce(extracted_text, '')));

create table public.research_document_sources (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.research_documents(id) on delete cascade,
  article_id bigint references public.articles(id) on delete set null,
  source_url text,
  title text,
  publisher text,
  published_at timestamptz,
  usefulness text not null default 'inbox' check (
    usefulness in ('inbox','useful','noise','archived')
  ),
  usefulness_reason text,
  captured_at timestamptz not null default now(),
  check (article_id is not null or source_url is not null)
);
create index idx_research_document_sources_document_id
  on public.research_document_sources(document_id);
create index idx_research_document_sources_usefulness_captured
  on public.research_document_sources(usefulness, captured_at desc);
create unique index idx_research_document_sources_article
  on public.research_document_sources(article_id)
  where article_id is not null;
create unique index idx_research_document_sources_url_document
  on public.research_document_sources(source_url, document_id)
  where source_url is not null;

create table public.research_document_annotations (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.research_documents(id) on delete cascade,
  entity_type text not null check (entity_type in ('market','symbol','theme','thesis')),
  entity_key text not null,
  relevance text not null default 'mentioned' check (
    relevance in ('primary','secondary','mentioned')
  ),
  sentiment text not null default 'unknown' check (
    sentiment in ('bullish','bearish','neutral','mixed','unknown')
  ),
  sentiment_score smallint check (sentiment_score between -100 and 100),
  confidence smallint not null default 50 check (confidence between 0 and 100),
  evidence_role text not null default 'context' check (
    evidence_role in ('supports','contradicts','context','unknown')
  ),
  rationale text,
  provenance text not null default 'manual' check (
    provenance in ('manual','ontology','model','import')
  ),
  model_version text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(document_id, entity_type, entity_key, provenance, model_version)
);
create index idx_research_document_annotations_document_id
  on public.research_document_annotations(document_id);
create index idx_research_document_annotations_entity
  on public.research_document_annotations(entity_type, entity_key, sentiment);

do $$
declare
  target_table text;
  sequence_name text;
begin
  foreach target_table in array array[
    'research_documents','research_document_sources','research_document_annotations'
  ]
  loop
    execute format('alter table public.%I enable row level security', target_table);
    execute format('revoke all on table public.%I from anon, authenticated', target_table);
    execute format('grant all on table public.%I to service_role', target_table);
    execute format(
      'grant select, insert, update on table public.%I to thesisforge_worker',
      target_table
    );
    execute format(
      'create policy thesisforge_worker_select on public.%I for select to thesisforge_worker using (true)',
      target_table
    );
    execute format(
      'create policy thesisforge_worker_insert on public.%I for insert to thesisforge_worker with check (true)',
      target_table
    );
    execute format(
      'create policy thesisforge_worker_update on public.%I for update to thesisforge_worker using (true) with check (true)',
      target_table
    );
    sequence_name := pg_get_serial_sequence(format('public.%I', target_table), 'id');
    if sequence_name is not null then
      execute format('grant usage, select on sequence %s to service_role', sequence_name);
      execute format('grant usage, select, update on sequence %s to thesisforge_worker', sequence_name);
    end if;
  end loop;
end $$;
