-- ThesisForge canonical Postgres schema.
-- Browser roles have no table privileges; trusted jobs and server routes use
-- the postgres connection or a Supabase secret key stored outside the repo.

create table public.runs (
  id bigint generated by default as identity primary key,
  run_type text not null,
  started_at timestamptz not null,
  completed_at timestamptz,
  notes text
);

create table public.bookmarks (
  id text primary key,
  author_id text,
  created_at timestamptz,
  fetched_at timestamptz not null,
  text text not null,
  raw_json jsonb not null,
  market_score smallint not null default 0 check (market_score between 0 and 100),
  is_market_related boolean not null default false
);

create table public.bookmark_urls (
  bookmark_id text not null references public.bookmarks(id) on delete cascade,
  url text not null,
  expanded_url text,
  display_url text,
  primary key (bookmark_id, url)
);

create table public.symbols (
  symbol text primary key,
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  mention_count bigint not null default 0 check (mention_count >= 0),
  source_count bigint not null default 0 check (source_count >= 0),
  status text not null default 'candidate'
);

create table public.bookmark_symbols (
  bookmark_id text not null references public.bookmarks(id) on delete cascade,
  symbol text not null references public.symbols(symbol) on delete cascade,
  source text not null,
  primary key (bookmark_id, symbol)
);
create index idx_bookmark_symbols_symbol on public.bookmark_symbols(symbol);

create table public.claims (
  id bigint generated by default as identity primary key,
  bookmark_id text not null references public.bookmarks(id) on delete cascade,
  claim_text text not null,
  claim_type text not null,
  created_at timestamptz not null,
  confidence smallint not null default 40 check (confidence between 0 and 100)
);
create index idx_claims_bookmark_id on public.claims(bookmark_id);

create table public.theses (
  id text primary key,
  name text not null,
  summary text not null,
  status text not null default 'forming',
  confidence smallint not null default 40 check (confidence between 0 and 100),
  time_horizon text not null default 'days_to_weeks',
  created_at timestamptz not null,
  updated_at timestamptz not null,
  stance text not null default 'neutral' check (stance in ('bullish', 'bearish', 'neutral')),
  variant_perception text,
  falsifier text
);

create table public.thesis_symbols (
  thesis_id text not null references public.theses(id) on delete cascade,
  symbol text not null references public.symbols(symbol) on delete cascade,
  role text not null default 'candidate',
  weight_hint double precision not null default 0,
  primary key (thesis_id, symbol)
);
create index idx_thesis_symbols_symbol on public.thesis_symbols(symbol);

create table public.thesis_evidence (
  id bigint generated by default as identity primary key,
  thesis_id text not null references public.theses(id) on delete cascade,
  bookmark_id text references public.bookmarks(id) on delete set null,
  evidence_type text not null,
  direction text not null,
  summary text not null,
  source_url text,
  confidence smallint not null default 40 check (confidence between 0 and 100),
  created_at timestamptz not null
);
create index idx_thesis_evidence_thesis_id on public.thesis_evidence(thesis_id);
create index idx_thesis_evidence_bookmark_id on public.thesis_evidence(bookmark_id);

create table public.thesis_scores (
  id bigint generated by default as identity primary key,
  thesis_id text not null references public.theses(id) on delete cascade,
  scored_at timestamptz not null,
  confidence smallint not null check (confidence between 0 and 100),
  momentum smallint not null check (momentum between 0 and 100),
  evidence_quality smallint not null check (evidence_quality between 0 and 100),
  catalyst_strength smallint not null check (catalyst_strength between 0 and 100),
  portfolio_fit smallint not null check (portfolio_fit between 0 and 100),
  risk smallint not null check (risk between 0 and 100),
  notes text
);
create index idx_thesis_scores_thesis_id on public.thesis_scores(thesis_id);

create table public.catalysts (
  id bigint generated by default as identity primary key,
  thesis_id text references public.theses(id) on delete set null,
  symbol text references public.symbols(symbol) on delete set null,
  catalyst_type text not null,
  event_date date,
  summary text not null,
  source text not null,
  status text not null default 'watching',
  created_at timestamptz not null
);
create index idx_catalysts_thesis_id on public.catalysts(thesis_id);
create index idx_catalysts_symbol on public.catalysts(symbol);

create table public.portfolio_exposure (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null,
  account_last4 text not null,
  symbol text not null,
  quantity numeric(28, 10) not null,
  average_buy_price numeric(20, 6),
  source text not null default 'robinhood_mcp'
);
create index idx_portfolio_exposure_symbol_observed on public.portfolio_exposure(symbol, observed_at desc);

create table public.account_snapshots (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null,
  account_label text not null,
  total_value numeric(20, 4) not null,
  equity_value numeric(20, 4) not null,
  cash numeric(20, 4) not null,
  buying_power numeric(20, 4) not null,
  source text not null default 'robinhood_mcp'
);
create index idx_account_snapshots_observed_at on public.account_snapshots(observed_at desc);

create table public.trade_proposals (
  id bigint generated by default as identity primary key,
  thesis_id text references public.theses(id) on delete set null,
  symbol text not null references public.symbols(symbol),
  side text not null check (side in ('buy', 'sell')),
  notional numeric(20, 4) not null check (notional >= 0),
  order_type text not null default 'market_review_only',
  status text not null default 'proposed',
  rationale text not null,
  created_at timestamptz not null,
  reviewed_at timestamptz,
  broker_alerts jsonb
);
create index idx_trade_proposals_thesis_id on public.trade_proposals(thesis_id);
create index idx_trade_proposals_symbol_status on public.trade_proposals(symbol, status);

create table public.postmortems (
  id bigint generated by default as identity primary key,
  trade_proposal_id bigint references public.trade_proposals(id) on delete set null,
  thesis_id text references public.theses(id) on delete set null,
  created_at timestamptz not null,
  outcome text not null,
  lesson text not null
);
create index idx_postmortems_trade_proposal_id on public.postmortems(trade_proposal_id);
create index idx_postmortems_thesis_id on public.postmortems(thesis_id);

create table public.articles (
  id bigint generated by default as identity primary key,
  bookmark_id text not null references public.bookmarks(id) on delete cascade,
  url text not null unique,
  title text,
  fetched_at timestamptz not null,
  status_code integer,
  content_type text,
  text text,
  error text
);
create index idx_articles_bookmark_id on public.articles(bookmark_id);

create table public.graph_nodes (
  id text primary key,
  node_type text not null,
  label text not null,
  properties_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table public.graph_edges (
  id bigint generated by default as identity primary key,
  src_id text not null references public.graph_nodes(id) on delete cascade,
  dst_id text not null references public.graph_nodes(id) on delete cascade,
  edge_type text not null,
  weight double precision not null default 1.0,
  evidence_count bigint not null default 1 check (evidence_count >= 0),
  properties_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  unique (src_id, dst_id, edge_type)
);
create index idx_graph_edges_src_id on public.graph_edges(src_id);
create index idx_graph_edges_dst_id on public.graph_edges(dst_id);

create table public.research_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  label text not null,
  event_date text,
  status text not null default 'watching',
  source_url text,
  summary text not null,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table public.research_queue (
  id bigint generated by default as identity primary key,
  priority smallint not null default 50 check (priority between 0 and 100),
  status text not null default 'open',
  topic text not null,
  reason text not null,
  source text not null,
  created_at timestamptz not null,
  updated_at timestamptz not null
);
create index idx_research_queue_status_priority on public.research_queue(status, priority desc);

create table public.predictions (
  id bigint generated by default as identity primary key,
  external_key text not null unique,
  thesis_id text not null references public.theses(id) on delete cascade,
  statement text not null,
  target_date date,
  probability smallint not null default 50 check (probability between 0 and 100),
  status text not null default 'open',
  resolution_notes text,
  created_at timestamptz not null,
  updated_at timestamptz not null
);
create index idx_predictions_thesis_status on public.predictions(thesis_id, status);

create table public.insights (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  summary text not null,
  insight_type text not null default 'derived',
  novelty smallint not null default 50 check (novelty between 0 and 100),
  confidence smallint not null default 50 check (confidence between 0 and 100),
  status text not null default 'active',
  created_at timestamptz not null,
  updated_at timestamptz not null
);
create index idx_insights_status on public.insights(status);

create table public.insight_links (
  insight_id bigint not null references public.insights(id) on delete cascade,
  node_id text not null references public.graph_nodes(id) on delete cascade,
  relationship text not null default 'connects',
  primary key (insight_id, node_id, relationship)
);
create index idx_insight_links_node_id on public.insight_links(node_id);

create table public.thesis_relations (
  src_thesis_id text not null references public.theses(id) on delete cascade,
  dst_thesis_id text not null references public.theses(id) on delete cascade,
  relation_type text not null,
  strength double precision not null default 1.0,
  rationale text not null,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  primary key (src_thesis_id, dst_thesis_id, relation_type)
);
create index idx_thesis_relations_dst_thesis_id on public.thesis_relations(dst_thesis_id);

create table public.event_decisions (
  event_id bigint primary key references public.research_events(id) on delete cascade,
  decision text not null default 'watch' check (decision in ('participate', 'watch', 'skip')),
  rationale text not null,
  participation_trigger text,
  decided_at timestamptz not null,
  updated_at timestamptz not null
);
create index idx_event_decisions_decision on public.event_decisions(decision);

create table public.research_cycles (
  id bigint generated by default as identity primary key,
  external_key text not null unique,
  thesis_id text not null references public.theses(id) on delete cascade,
  hypothesis text not null,
  preregistered_outcome text not null,
  preregistered_at timestamptz not null,
  stage text not null default 'research',
  status text not null default 'open',
  iteration integer not null default 1 check (iteration > 0),
  market_regime text,
  created_at timestamptz not null,
  updated_at timestamptz not null
);
create index idx_research_cycles_stage on public.research_cycles(stage, status);
create index idx_research_cycles_thesis_id on public.research_cycles(thesis_id);

create table public.strategy_tests (
  id bigint generated by default as identity primary key,
  external_key text not null unique,
  cycle_id bigint not null references public.research_cycles(id) on delete cascade,
  variant_label text not null,
  status text not null default 'queued',
  total_return double precision,
  max_drawdown double precision,
  deflated_sharpe double precision,
  cost_multiplier double precision not null default 1.0 check (cost_multiplier >= 0),
  stress_regime text,
  failure_reason text,
  autopsy text,
  tested_at timestamptz not null
);
create index idx_strategy_tests_cycle_status on public.strategy_tests(cycle_id, status);

create table public.test_scenarios (
  id bigint generated by default as identity primary key,
  test_id bigint not null references public.strategy_tests(id) on delete cascade,
  scenario_key text not null,
  market_regime text not null,
  cost_multiplier double precision not null check (cost_multiplier >= 0),
  outcome text not null,
  metric_value double precision,
  breach_type text,
  tested_at timestamptz not null,
  unique (test_id, scenario_key)
);
create index idx_test_scenarios_test_outcome on public.test_scenarios(test_id, outcome);

create table public.agent_runs (
  id bigint generated by default as identity primary key,
  cycle_id bigint not null references public.research_cycles(id) on delete cascade,
  agent_role text not null,
  independence_group text,
  price_blinded boolean not null default false,
  status text not null default 'complete',
  summary text not null,
  created_at timestamptz not null
);
create index idx_agent_runs_cycle_id on public.agent_runs(cycle_id);

create table public.research_lessons (
  id bigint generated by default as identity primary key,
  cycle_id bigint not null references public.research_cycles(id) on delete cascade,
  test_id bigint references public.strategy_tests(id) on delete set null,
  thesis_id text not null references public.theses(id) on delete cascade,
  lesson_type text not null,
  summary text not null,
  market_regime text,
  incorporated boolean not null default false,
  created_at timestamptz not null
);
create index idx_research_lessons_cycle_id on public.research_lessons(cycle_id);
create index idx_research_lessons_test_id on public.research_lessons(test_id);
create index idx_research_lessons_thesis on public.research_lessons(thesis_id, incorporated);

create table public.risk_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  scope text not null,
  control_type text not null,
  threshold_json jsonb not null,
  enforcement_level text not null default 'code',
  status text not null default 'active',
  updated_at timestamptz not null
);

create table public.financial_api_requests (
  id bigint generated by default as identity primary key,
  provider text not null,
  request_fingerprint text not null,
  method text not null,
  endpoint text not null,
  params_json jsonb not null default '{}'::jsonb,
  body_json jsonb,
  requested_at timestamptz not null,
  completed_at timestamptz not null,
  status_code integer not null,
  response_headers_json jsonb not null default '{}'::jsonb,
  response_sha256 text not null,
  response_encoding text not null default 'gzip',
  response_body bytea not null,
  error_text text
);
create index idx_financial_requests_fingerprint on public.financial_api_requests(request_fingerprint, completed_at desc);

create table public.financial_request_cache (
  request_fingerprint text primary key,
  request_id bigint not null references public.financial_api_requests(id) on delete cascade,
  cached_at timestamptz not null,
  expires_at timestamptz not null,
  freshness_policy text not null
);
create index idx_financial_request_cache_request_id on public.financial_request_cache(request_id);

create table public.financial_access_log (
  id bigint generated by default as identity primary key,
  request_fingerprint text not null,
  request_id bigint references public.financial_api_requests(id) on delete set null,
  access_type text not null check (access_type in ('network', 'cache', 'dry_run', 'blocked')),
  accessed_at timestamptz not null,
  detail text
);
create index idx_financial_access_type_date on public.financial_access_log(access_type, accessed_at desc);
create index idx_financial_access_log_request_id on public.financial_access_log(request_id);

create table public.financial_records (
  id bigint generated by default as identity primary key,
  provider text not null,
  dataset text not null,
  ticker text,
  record_key text not null,
  period text,
  report_period date,
  filing_date date,
  fetched_at timestamptz not null,
  record_sha256 text not null,
  payload_json jsonb not null,
  source_request_id bigint not null references public.financial_api_requests(id) on delete cascade,
  unique (provider, dataset, record_key, record_sha256)
);
create index idx_financial_records_ticker_dataset on public.financial_records(ticker, dataset, report_period desc);
create index idx_financial_records_source_request on public.financial_records(source_request_id);

create table public.dashboard_snapshots (
  id text primary key,
  generated_at timestamptz not null,
  payload jsonb not null
);

-- Supabase exposes public by default. Keep every table deny-by-default for
-- browser roles; trusted server jobs use service_role or a Postgres connection.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'runs','bookmarks','bookmark_urls','symbols','bookmark_symbols','claims','theses',
    'thesis_symbols','thesis_evidence','thesis_scores','catalysts','portfolio_exposure',
    'account_snapshots','trade_proposals','postmortems','articles','graph_nodes','graph_edges',
    'research_events','research_queue','predictions','insights','insight_links','thesis_relations',
    'event_decisions','research_cycles','strategy_tests','test_scenarios','agent_runs',
    'research_lessons','risk_controls','financial_api_requests','financial_request_cache',
    'financial_access_log','financial_records','dashboard_snapshots'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
    execute format('grant all on table public.%I to service_role', table_name);
  end loop;
end $$;

grant usage on schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
alter default privileges in schema public revoke all on tables from anon, authenticated;
alter default privileges in schema public grant all on tables to service_role;
alter default privileges in schema public grant usage, select on sequences to service_role;
