/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.broker.jsonc --include-runtime=false worker-broker-configuration.d.ts` (hash: bec9c4ad1a5057d2daf896d27b7e1133)
interface __BaseEnv_Env {
	BROKER_PUBLIC_ORIGIN: "https://thesisforge-broker-gateway.davidwallach2.workers.dev";
	ROBINHOOD_OAUTH_CALLBACK_ORIGIN: "http://127.0.0.1:18789";
	ROBINHOOD_MCP_URL: "https://agent.robinhood.com/mcp/trading";
	BROKER_EXECUTION_ENABLED: "true";
	CF_ACCESS_TEAM_DOMAIN: string;
	CF_ACCESS_AUD: string;
	BROKER_OWNER_EMAIL: string;
	ROBINHOOD_BROKER_AGENT: DurableObjectNamespace<import("./workflows/robinhood-broker-agent").RobinhoodBrokerAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workflows/robinhood-broker-agent");
		durableNamespaces: "RobinhoodBrokerAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BROKER_PUBLIC_ORIGIN" | "ROBINHOOD_OAUTH_CALLBACK_ORIGIN" | "ROBINHOOD_MCP_URL" | "BROKER_EXECUTION_ENABLED" | "CF_ACCESS_TEAM_DOMAIN" | "CF_ACCESS_AUD" | "BROKER_OWNER_EMAIL">> {}
}
