/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.publication.jsonc --include-runtime=false worker-publication-configuration.d.ts` (hash: 3e304a8379acf9718926cb5bec5f3a50)
interface __BaseEnv_Env {
	RESEARCH_TASK_QUEUE: Queue;
	AI: Ai;
	AI_GATEWAY_ID: "default";
	TRADING_ENABLED: "true";
	BROKER_GATEWAY_MODE: "robinhood_mcp";
	SUPABASE_URL: string;
	THESISFORGE_PUBLICATION_TOKEN: string;
	THESIS_COORDINATOR: DurableObjectNamespace<import("./workflows/cloud-native-control").ThesisCoordinator>;
	POSITION_MONITOR: DurableObjectNamespace<import("./workflows/cloud-native-control").PositionMonitor>;
	BROKER_EXECUTION_COORDINATOR: DurableObjectNamespace<import("./workflows/cloud-native-control").BrokerExecutionCoordinator>;
	ROBINHOOD_BROKER_AGENT: DurableObjectNamespace /* RobinhoodBrokerAgent from thesisforge-broker-gateway */;
	DASHBOARD_PUBLICATION: Workflow<Parameters<import("./workflows/cloud-native-control").DashboardPublicationWorkflow['run']>[0]['payload']>;
	CLOUD_RESEARCH_CYCLE: Workflow<Parameters<import("./workflows/cloud-native-control").CloudResearchWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workflows/cloud-native-control");
		durableNamespaces: "ThesisCoordinator" | "PositionMonitor" | "BrokerExecutionCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_GATEWAY_ID" | "TRADING_ENABLED" | "BROKER_GATEWAY_MODE" | "SUPABASE_URL" | "THESISFORGE_PUBLICATION_TOKEN">> {}
}
