/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 0ca3bbb897fecb628edf69b168fc110d)
interface __BaseEnv_Env {
	SUPABASE_URL: string;
	SUPABASE_PUBLISHABLE_KEY: string;
	THESISFORGE_DASHBOARD_TOKEN: string;
	THESISFORGE_MANAGER_TOKEN: string;
	THESISFORGE_MANAGER_USER_IDS: string;
	CF_ACCESS_TEAM_DOMAIN: string;
	CF_ACCESS_AUD: string;
	INTERNAL_SERVICE_TOKEN: string;
	KNOWLEDGE_PIPELINE: Fetcher /* thesisforge-knowledge-pipeline */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY" | "THESISFORGE_DASHBOARD_TOKEN" | "THESISFORGE_MANAGER_TOKEN" | "THESISFORGE_MANAGER_USER_IDS" | "CF_ACCESS_TEAM_DOMAIN" | "CF_ACCESS_AUD" | "INTERNAL_SERVICE_TOKEN">> {}
}
