/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.knowledge.jsonc --include-runtime=false worker-knowledge-configuration.d.ts` (hash: 7e24415de7acebf0582e66d69f851dd7)
interface __BaseEnv_Env {
	RESEARCH_ORIGINALS: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	ARTICLE_QUEUE: Queue;
	X_REDIRECT_URI: "https://thesisforge-dashboard.davidwallach2.workers.dev/api/x/callback";
	SUPABASE_URL: string;
	THESISFORGE_PUBLICATION_TOKEN: string;
	X_CLIENT_ID: string;
	X_ACCESS_TOKEN: string;
	X_REFRESH_TOKEN: string;
	X_CREDENTIAL_VAULT: DurableObjectNamespace<import("./knowledge/knowledge-pipeline").XCredentialVault>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./knowledge/knowledge-pipeline");
		durableNamespaces: "XCredentialVault";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "X_REDIRECT_URI" | "SUPABASE_URL" | "THESISFORGE_PUBLICATION_TOKEN" | "X_CLIENT_ID" | "X_ACCESS_TOKEN" | "X_REFRESH_TOKEN">> {}
}
