/* eslint-disable */
// Generated by Wrangler from wrangler.research.jsonc for thesisforge-research-orchestrator.
interface __BaseEnv_Env {
	RESEARCH_TASK_QUEUE: Queue;
	AI: Ai;
	AI_GATEWAY_ID: "default";
	TRADING_ENABLED: "true";
	BROKER_GATEWAY_MODE: "robinhood_mcp";
	SUPABASE_URL: string;
	THESISFORGE_PUBLICATION_TOKEN: string;
	THESIS_COORDINATOR: DurableObjectNamespace<import("./workflows/research-orchestrator").ThesisCoordinator>;
	POSITION_MONITOR: DurableObjectNamespace<import("./workflows/research-orchestrator").PositionMonitor>;
	BROKER_EXECUTION_COORDINATOR: DurableObjectNamespace<import("./workflows/research-orchestrator").BrokerExecutionCoordinator>;
	ROBINHOOD_BROKER_AGENT: DurableObjectNamespace /* RobinhoodBrokerAgent from thesisforge-broker-gateway */;
	CLOUD_RESEARCH_CYCLE: Workflow<Parameters<import("./workflows/research-orchestrator").CloudResearchWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workflows/research-orchestrator");
		durableNamespaces: "ThesisCoordinator" | "PositionMonitor" | "BrokerExecutionCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_GATEWAY_ID" | "TRADING_ENABLED" | "BROKER_GATEWAY_MODE" | "SUPABASE_URL" | "THESISFORGE_PUBLICATION_TOKEN">> {}
}
